'use strict';
module.exports = {
  version: 'Version 1.0, valid from 8 October 2026. The Dutch text prevails; translations are provided for convenience.',
  voorwaarden: {
    title: 'Terms and conditions',
    meta: 'Woonwekker terms and conditions: a search and alert service, not an estate agent or intermediary. Bellen subscription, free day, price, renewal and cancellation.',
    sections: [
      ['1. Who we are', 'Vorxeo (Woonwekker), registered with the Dutch Chamber of Commerce (KvK) under number 42108778, VAT number NL005499683B86 (‘we’). Woonwekker is a business division of Vorxeo.'],
      ['2. What Woonwekker is', 'Woonwekker is a search and alert service. We are not an estate agent or intermediary and do not rent out homes. Listings come from public ads on other websites; you contact the advertiser directly.', 'We do not act on behalf of landlords or tenants, do not conclude rental agreements and do not handle rental applications. For every home we show the source and the date we last checked the ad.'],
      ['3. No intermediation, no guarantee', 'We do not charge agency fees. We do not guarantee that a home is still available, that the information in an ad is correct or that you will get a home. Always check price, conditions and availability in the original ad and with the advertiser.'],
      ['4. Kijken (free)', 'Searching, filtering, favourites, search profiles and the link to the original ad are free, with or without an account. Contact details and links to ads are never behind a paid subscription.'],
      ['5. Bellen (paid subscription)', 'Bellen is an optional subscription for speed and extras: instant email alerts as soon as a matching home comes in, extra filters, priority notifications, the reply kit, the document checklist and one search buddy. Bellen does not give access to advertisers’ contact details; those are free for everyone.', 'The total price is €18.50 per month. On a first signup the first day is free. After that the subscription renews automatically every month for an indefinite period and you pay €18.50 per month until you cancel.', 'New subscriptions are temporarily unavailable at the moment.'],
      ['6. Cancelling', 'You can cancel Bellen online at any time via ‘Cancel subscription’ at the bottom of every page or in your account, with no notice period. After cancelling nothing more is charged. You keep access until the end of the period you have already paid for. If you cancel during the free day, you pay nothing.'],
      ['7. Right of withdrawal', 'You have a 14-day cooling-off period from the day the subscription is concluded. During that period you can withdraw from the contract without giving a reason via ‘Withdraw from contract’, also without logging in. If you asked for Bellen to start immediately, on withdrawal you pay a proportionate amount for the period in which Bellen was already provided. The Right of withdrawal page contains the full information and the model form.'],
      ['8. Refunds', 'We make refunds within 14 days, using the same means of payment you used. See the cancellation and refund policy.'],
      ['9. Other people’s ads', 'Ads, photos and texts belong to the advertisers and the websites where they appear. We link to the original ad. Responding, viewings and renting happen outside Woonwekker, under the terms of that website and that advertiser.'],
      ['10. Liability', 'We are not liable for the content of other people’s ads or for arrangements you make with an advertiser, except in case of intent or deliberate recklessness on our part. Your statutory rights as a consumer always apply. Never transfer money based only on an ad.'],
      ['11. Changes', 'We may change these terms. We announce changes that affect a running subscription in advance; you can then cancel free of charge.'],
      ['12. Applicable law', 'These terms are governed by Dutch law. As a consumer you keep the protection of the mandatory rules of the country where you live.'],
    ],
  },
  privacy: {
    title: 'Privacy statement',
    meta: 'Vorxeo (Woonwekker) privacy statement: what data the site processes, Google Ads after consent, email via Resend, hosting and your rights.',
    intro: 'Only what this website actually does with data.',
    sections: [
      ['Controller', 'Woonwekker is the controller for processing on this website. KvK number 42108778. VAT number NL005499683B86.'],
      'KEEP:1',
      'KEEP:2',
      ['Payments', 'No new payments are being processed at the moment; new subscriptions are temporarily unavailable. For an existing Bellen subscription the site sets a signed cookie, ww_bellen, so that your access on this device follows the status of your subscription. Payment data for an existing subscription is processed by the payment provider you paid with. As soon as a payment provider is active again, we will name it here before you can pay.'],
      ['Email via Resend', 'The confirmation email on signup and emails about your subscription, cancellation or withdrawal are sent through Resend, if an API key is configured on the server. Without a key that email is not sent.'],
      ['Cancelling and withdrawing', 'If you use the ‘Cancel subscription’ or ‘Withdraw from contract’ form, we process your name, your email address, the order date if you enter it, and the time of receipt. We do this to carry out your request and to be able to prove it was received in time (legal obligation).'],
      'KEEP:5',
      'KEEP:6',
      ['Hosting and photos', 'The site runs on Vercel. When you open pages, Vercel receives technical request data, such as IP address and browser type, needed to show the page. Photos of homes are loaded directly from the image servers of the source websites, which also receive your IP address. When you open an original ad, that website’s privacy policy applies.'],
      'KEEP:8',
    ],
  },
  terugbetaling: {
    title: 'Cancellation and refund policy',
    meta: 'Cancelling and refunds for Woonwekker Bellen: cancel online at any time, access until the end of the paid period, withdraw within 14 days.',
    sections: [
      ['Cancelling', 'You can cancel Bellen online at any time via ‘Cancel subscription’, with no notice period and without logging in. After cancelling nothing more is charged. You keep access until the end of the period you have already paid for; there is no partial refund for that period, except when you withdraw within the cooling-off period.'],
      ['Free day', 'If you cancel during the free first day, you pay nothing.'],
      ['Withdrawing within 14 days', 'If you withdraw within 14 days of concluding the subscription, we refund everything you paid. If you asked for Bellen to start immediately, we keep a proportionate amount for the period in which Bellen was already provided.'],
      ['How and when', 'We refund within 14 days of receiving your withdrawal, using the same means of payment you used, unless you expressly agree otherwise. The refund costs you nothing.'],
      ['Incorrect charge', 'If anything is charged after you cancelled or withdrew, we refund it in full.'],
    ],
  },
  herroeping: {
    title: 'Right of withdrawal',
    meta: 'Right of withdrawal for Woonwekker Bellen: 14-day cooling-off period, model withdrawal form and the Withdraw from contract button.',
    sections: [
      ['Right of withdrawal', 'You have the right to withdraw from the Bellen contract within 14 days without giving any reason. The withdrawal period expires 14 days after the day the contract was concluded.'],
      ['How to withdraw', 'Use the ‘Withdraw from contract’ button below; no login is needed. You may also use the model form or send another unequivocal statement, but this is not required. To meet the deadline it is enough to send your statement before the 14 days have passed.'],
      ['Effects of withdrawal', 'If you withdraw, we will refund all payments you made for Bellen without undue delay and in any event within 14 days of receiving your withdrawal. We use the same means of payment you used, unless you expressly agree otherwise; the refund costs you nothing.', 'If you requested Bellen to begin during the withdrawal period, you pay an amount proportionate to what has been provided until you tell us you are withdrawing, compared with full performance of the contract.'],
      ['Confirmation of receipt', 'After sending you immediately see a confirmation with date, time and reference. Keep it. If email sending is configured, we also send the confirmation by email.'],
    ],
    modelTitle: 'Model withdrawal form',
    modelNote: '(complete and return this form only if you wish to withdraw from the contract)',
    modelLines: [
      'To: Vorxeo (Woonwekker), KvK number 42108778. You can submit it via the ‘Withdraw from contract’ form on this page.',
      'I/We* hereby give notice that I/We* withdraw from my/our* contract for the provision of the following service: Woonwekker Bellen',
      'Ordered on* [order date]',
      '[Name of consumer(s)]',
      '[Address of consumer(s)]',
      '[Signature of consumer(s)] (only if this form is notified on paper)',
      '[Date (DD-MM-YYYY)]',
    ],
    modelFoot: '* Delete as appropriate.',
    formTitle: 'Withdraw from contract',
    formIntro: 'Enter the name and email address you signed up with. No login needed.',
  },
  opzeggen: {
    title: 'Cancel subscription',
    meta: 'Cancel your Woonwekker Bellen subscription online, with no notice period and without logging in.',
    paragraphs: [
      'Here you cancel your Bellen subscription. There is no notice period.',
      'After cancelling nothing more is charged. You keep access until the end of the period you have already paid for. If you cancel during the free day, you pay nothing.',
      'Enter the name and email address you signed up with and click ‘Cancel subscription’. No login needed. You see a confirmation immediately.',
    ],
    withdrawHint: 'Want to withdraw from the contract within 14 days of signing up and get your money back? Use',
  },
  faqNew: {
    what: ['What is Woonwekker?', 'Woonwekker is a search and alert service. We are not an estate agent or intermediary and do not rent out homes. Listings come from public ads on other websites; you contact the advertiser directly.'],
    sources: ['Where do the listings come from?', 'From public ads on other websites: external property platforms. Every home shows the source and the date we last checked the ad.'],
    fresh: ['Are the homes still available?', 'We cannot be sure. We do not show ads that are ‘under negotiation’ or unavailable at the source, and we hide ads we have not checked for more than {days} days. Always check the current status in the original ad.'],
    contact: ['How do I contact the advertiser or book a viewing?', 'Open a home and choose ‘View the original ad’. You respond directly to the advertiser, on that website. That is free on Woonwekker. The source website has its own terms. External property platforms may require their own account or payment to respond. This is separate from Woonwekker.'],
    pay: ['Do I have to pay to search?', 'No. Searching, filtering and the link to the original ad are free. Bellen is an optional subscription for faster alerts, extra filters and priority notifications: 1 day free, then a total price of €18.50 per month, renewing automatically until you cancel. Contact details and links to ads are never behind Bellen. New subscriptions are temporarily unavailable.'],
    alerts: ['Do I get notified about new homes?', 'You set up search profiles and email notifications under Account. With Kijken you get at most 3 email alerts per week; with Bellen, instant email alerts and priority notifications.'],
    photos: ['Why does a home have only a few photos?', 'We show the photos from the original ad, as the source website provides them. More photos and details are in the original ad.'],
    cancel: ['How do I cancel or withdraw from the contract?', 'Via ‘Cancel subscription’ at the bottom of every page and in your account, with no notice period. You keep access until the end of the paid period. Within 14 days of signing up you can withdraw from the contract via ‘Withdraw from contract’, also without logging in.'],
  },
  insightA3: {
    title: 'Free search vs Bellen €18.50: what you pay for on Woonwekker',
    intro: 'Searching and contacting the advertiser are free. Bellen is only about speed and extras.',
    body: '<p>Many rental sites mix up “creating an account” and “paying”. On Woonwekker those are separate, and contacting an advertiser belongs to neither: it is always free.</p>\n<p><strong>Free (Kijken).</strong> You browse, filter and save search profiles. Every home shows the source and the date of the last check. One click opens the original ad on the website where it appears, and there you respond directly to the advertiser.</p>\n<p><strong>Bellen: 1 day free, then a total price of €18.50 per month.</strong> Bellen is an optional subscription for speed and extras: instant email alerts, extra filters and priority notifications. It renews every month until you cancel. You can always cancel online via <a href="/opzeggen/">Cancel subscription</a>. New subscriptions are temporarily unavailable.</p>\n<p><strong>What Bellen is not.</strong> Woonwekker is not an estate agent or intermediary and does not rent out homes. Bellen is not access to contact details and not a guarantee that you will get a home. The rules are in the <a href="/voorwaarden/">terms and conditions</a>; prices and details are on <a href="/prijzen/">pricing</a>.</p>',
  },
};
