'use strict';
module.exports = {
  version: 'Versión 1.0, válida desde el 8 de octubre de 2026. Prevalece el texto neerlandés; las traducciones son una ayuda.',
  voorwaarden: {
    title: 'Condiciones generales',
    meta: 'Condiciones generales de Woonwekker: servicio de búsqueda y alertas, no agencia inmobiliaria ni intermediario. Suscripción Bellen, día gratis, precio, renovación y cancelación.',
    sections: [
      ['1. Quiénes somos', 'Woonwekker, inscrita en la Cámara de Comercio neerlandesa (KvK) con el número 42108778, número de IVA NL005499683B86 («nosotros»).'],
      ['2. Qué es Woonwekker', 'Woonwekker es un servicio de búsqueda y alertas. No somos una agencia inmobiliaria ni un intermediario y no alquilamos viviendas. La oferta procede de anuncios públicos en otros sitios web; contactas directamente con el anunciante.', 'No actuamos por encargo de arrendadores ni de inquilinos, no celebramos contratos de alquiler ni tramitamos solicitudes de alquiler. En cada vivienda mostramos la fuente y la fecha en que comprobamos el anuncio por última vez.'],
      ['3. Sin intermediación, sin garantía', 'No cobramos honorarios de intermediación. No garantizamos que una vivienda siga disponible, que los datos de un anuncio sean correctos ni que consigas una vivienda. Comprueba siempre el precio, las condiciones y la disponibilidad en el anuncio original y con el anunciante.'],
      ['4. Kijken (gratis)', 'Buscar, filtrar, favoritos, perfiles de búsqueda y el enlace al anuncio original son gratis, con o sin cuenta. Los datos de contacto y los enlaces a los anuncios nunca están detrás de una suscripción de pago.'],
      ['5. Bellen (suscripción de pago)', 'Bellen es una suscripción opcional para ganar velocidad y extras: alertas por correo inmediatas en cuanto llega una vivienda que encaja, filtros adicionales, prioridad en las notificaciones, el kit de respuesta, la lista de documentos y un compañero de búsqueda. Bellen no da acceso a los datos de contacto de los anunciantes; esos son gratis para todos.', 'El precio total es de 18,50 € al mes. En la primera alta, el primer día es gratis. Después la suscripción se renueva automáticamente cada mes por tiempo indefinido y pagas 18,50 € al mes hasta que la canceles.', 'En este momento las nuevas suscripciones no están disponibles temporalmente.'],
      ['6. Cancelar', 'Puedes cancelar Bellen en línea en cualquier momento mediante «Cancelar suscripción», al pie de cada página o en tu cuenta, sin plazo de preaviso. Tras cancelar no se cobra nada más. Mantienes el acceso hasta el final del periodo que ya has pagado. Si cancelas durante el día gratis, no pagas nada.'],
      ['7. Derecho de desistimiento', 'Tienes 14 días de desistimiento desde la celebración de la suscripción. En ese plazo puedes desistir del contrato sin indicar el motivo mediante «Desistir del contrato», también sin iniciar sesión. Si pediste que Bellen empezara de inmediato, al desistir pagas un importe proporcional al periodo en que Bellen ya se prestó. En la página Derecho de desistimiento encontrarás la información completa y el formulario modelo.'],
      ['8. Reembolsos', 'Reembolsamos en un plazo de 14 días, con el mismo medio de pago que utilizaste. Consulta la política de cancelación y reembolso.'],
      ['9. Anuncios de terceros', 'Los anuncios, fotos y textos pertenecen a los anunciantes y a los sitios web donde aparecen. Enlazamos al anuncio original. Responder, visitar y alquilar se hace fuera de Woonwekker, según las condiciones de ese sitio web y de ese anunciante.'],
      ['10. Responsabilidad', 'No somos responsables del contenido de anuncios de terceros ni de los acuerdos que hagas con un anunciante, salvo dolo o imprudencia consciente por nuestra parte. Tus derechos legales como consumidor se mantienen siempre. Nunca transfieras dinero basándote solo en un anuncio.'],
      ['11. Cambios', 'Podemos modificar estas condiciones. Los cambios que afecten a una suscripción en curso los anunciamos con antelación; entonces puedes cancelar sin coste.'],
      ['12. Derecho aplicable', 'Estas condiciones se rigen por el derecho neerlandés. Como consumidor conservas la protección de las normas imperativas del país donde vives.'],
    ],
  },
  privacy: {
    title: 'Declaración de privacidad',
    meta: 'Declaración de privacidad de Woonwekker: qué datos trata el sitio, Google Ads tras el consentimiento, correo mediante Resend, alojamiento y tus derechos.',
    intro: 'Solo lo que este sitio web hace realmente con los datos.',
    sections: [
      ['Responsable', 'Woonwekker es el responsable del tratamiento en este sitio web. Número KvK 42108778. Número de IVA NL005499683B86.'],
      'KEEP:1',
      'KEEP:2',
      ['Pagos', 'En este momento no se procesan pagos nuevos; las nuevas suscripciones no están disponibles temporalmente. Para una suscripción Bellen existente, el sitio coloca una cookie firmada, ww_bellen, para que tu acceso en este dispositivo siga el estado de tu suscripción. Los datos de pago de una suscripción existente los trata el proveedor de pagos con el que pagaste. En cuanto vuelva a estar activo un proveedor de pagos, lo indicaremos aquí antes de que puedas pagar.'],
      ['Correo mediante Resend', 'El correo de confirmación al registrarte y los correos sobre tu suscripción, cancelación o desistimiento se envían mediante Resend, si hay una clave API en el servidor. Sin clave, ese correo no se envía.'],
      ['Cancelar y desistir', 'Si usas el formulario «Cancelar suscripción» o «Desistir del contrato», tratamos tu nombre, tu correo electrónico, la fecha del pedido si la indicas y la hora de recepción. Lo hacemos para tramitar tu solicitud y poder demostrar que se recibió a tiempo (obligación legal).'],
      'KEEP:5',
      'KEEP:6',
      ['Alojamiento y fotos', 'El sitio funciona en Vercel. Al abrir páginas, Vercel recibe datos técnicos de la solicitud, como la dirección IP y el tipo de navegador, necesarios para mostrar la página. Las fotos de las viviendas se cargan directamente desde los servidores de imágenes de los sitios de origen (Funda, Kamernet, Pararius), que también reciben tu dirección IP. Cuando abres un anuncio original, se aplica la política de privacidad de ese sitio web.'],
      'KEEP:8',
    ],
  },
  terugbetaling: {
    title: 'Política de cancelación y reembolso',
    meta: 'Cancelación y reembolso de Woonwekker Bellen: cancela en línea cuando quieras, acceso hasta el final del periodo pagado, desistimiento en 14 días.',
    sections: [
      ['Cancelar', 'Puedes cancelar Bellen en línea en cualquier momento mediante «Cancelar suscripción», sin plazo de preaviso y sin iniciar sesión. Tras cancelar no se cobra nada más. Mantienes el acceso hasta el final del periodo que ya has pagado; por ese periodo no hay reembolso parcial, salvo si desistes dentro del plazo de desistimiento.'],
      ['Día gratis', 'Si cancelas durante el primer día gratis, no pagas nada.'],
      ['Desistir en 14 días', 'Si desistes en los 14 días siguientes a la celebración de la suscripción, te devolvemos todo lo que pagaste. Si pediste que Bellen empezara de inmediato, retenemos un importe proporcional al periodo en que Bellen ya se prestó.'],
      ['Cómo y cuándo', 'Reembolsamos en un plazo de 14 días desde que recibimos tu desistimiento, con el mismo medio de pago que utilizaste, salvo que aceptes expresamente otra cosa. El reembolso no te cuesta nada.'],
      ['Cargo indebido', 'Si se cobra algo después de que cancelaste o desististe, te lo devolvemos íntegramente.'],
    ],
  },
  herroeping: {
    title: 'Derecho de desistimiento',
    meta: 'Derecho de desistimiento de Woonwekker Bellen: 14 días, formulario modelo de desistimiento y el botón Desistir del contrato.',
    sections: [
      ['Derecho de desistimiento', 'Tienes derecho a desistir del contrato de Bellen en un plazo de 14 días sin necesidad de justificación. El plazo de desistimiento expira a los 14 días de la celebración del contrato.'],
      ['Cómo desistir', 'Usa el botón «Desistir del contrato» de abajo; no hace falta iniciar sesión. También puedes usar el formulario modelo o enviar otra declaración inequívoca, pero no es obligatorio. Para cumplir el plazo basta con que envíes tu declaración antes de que terminen los 14 días.'],
      ['Consecuencias del desistimiento', 'Si desistes, te devolveremos todos los pagos que hiciste por Bellen sin demoras indebidas y, en cualquier caso, a más tardar 14 días después de recibir tu desistimiento. Usaremos el mismo medio de pago que utilizaste, salvo que aceptes expresamente otra cosa; el reembolso no te cuesta nada.', 'Si solicitaste que Bellen empezara durante el plazo de desistimiento, pagarás un importe proporcional a lo prestado hasta el momento en que nos comuniques el desistimiento, en relación con el total del contrato.'],
      ['Acuse de recibo', 'Tras el envío verás de inmediato una confirmación con fecha, hora y referencia. Guárdala. Si el envío de correo está configurado, también te enviaremos la confirmación por correo.'],
    ],
    modelTitle: 'Modelo de formulario de desistimiento',
    modelNote: '(solo debe cumplimentar y enviar el presente formulario si desea desistir del contrato)',
    modelLines: [
      'A la atención de: Woonwekker, número KvK 42108778. Puede presentarlo mediante el formulario «Desistir del contrato» de esta página.',
      'Por la presente le comunico/comunicamos* que desisto de/desistimos de* mi/nuestro* contrato de prestación del siguiente servicio: Woonwekker Bellen',
      'Pedido el* [fecha del pedido]',
      '[Nombre del consumidor o de los consumidores]',
      '[Domicilio del consumidor o de los consumidores]',
      '[Firma del consumidor o de los consumidores] (solo si el presente formulario se presenta en papel)',
      '[Fecha (DD-MM-AAAA)]',
    ],
    modelFoot: '* Táchese lo que no proceda.',
    formTitle: 'Desistir del contrato',
    formIntro: 'Indica el nombre y el correo electrónico con los que te registraste. No hace falta iniciar sesión.',
  },
  opzeggen: {
    title: 'Cancelar suscripción',
    meta: 'Cancela tu suscripción Woonwekker Bellen en línea, sin plazo de preaviso y sin iniciar sesión.',
    paragraphs: [
      'Aquí cancelas tu suscripción Bellen. No hay plazo de preaviso.',
      'Tras cancelar no se cobra nada más. Mantienes el acceso hasta el final del periodo que ya has pagado. Si cancelas durante el día gratis, no pagas nada.',
      'Indica el nombre y el correo electrónico con los que te registraste y pulsa «Cancelar suscripción». No hace falta iniciar sesión. Verás una confirmación de inmediato.',
    ],
    withdrawHint: '¿Quieres desistir del contrato en los 14 días siguientes al alta y recuperar tu dinero? Usa',
  },
  faqNew: {
    what: ['¿Qué es Woonwekker?', 'Woonwekker es un servicio de búsqueda y alertas. No somos una agencia inmobiliaria ni un intermediario y no alquilamos viviendas. La oferta procede de anuncios públicos en otros sitios web; contactas directamente con el anunciante.'],
    sources: ['¿De dónde viene la oferta?', 'De anuncios públicos en otros sitios web: {sources}. Cada vivienda muestra la fuente y la fecha en que comprobamos el anuncio por última vez.'],
    fresh: ['¿Siguen disponibles las viviendas?', 'No lo sabemos con seguridad. No mostramos anuncios que en la fuente están «en negociación» o no disponibles, y ocultamos los anuncios que no hemos comprobado en más de {days} días. Comprueba siempre el estado actual en el anuncio original.'],
    contact: ['¿Cómo contacto con el anunciante o reservo una visita?', 'Abre una vivienda y elige «Ver el anuncio original». Respondes directamente al anunciante, en ese sitio web. En Woonwekker es gratis. El sitio de origen tiene sus propias condiciones; en Kamernet puede que necesites una cuenta de pago de Kamernet para responder.'],
    pay: ['¿Tengo que pagar para buscar?', 'No. Buscar, filtrar y el enlace al anuncio original son gratis. Bellen es una suscripción opcional para alertas más rápidas, filtros adicionales y prioridad en las notificaciones: 1 día gratis, después precio total 18,50 € al mes, con renovación automática hasta que canceles. Los datos de contacto y los enlaces a los anuncios nunca están detrás de Bellen. Las nuevas suscripciones no están disponibles temporalmente.'],
    alerts: ['¿Recibo avisos de viviendas nuevas?', 'Configuras perfiles de búsqueda y avisos por correo en Cuenta. Con Kijken recibes como máximo 3 alertas por correo a la semana; con Bellen, alertas por correo inmediatas y prioridad en las notificaciones.'],
    photos: ['¿Por qué una vivienda tiene solo unas pocas fotos?', 'Mostramos las fotos del anuncio original, tal como las ofrece el sitio de origen. En el anuncio original encontrarás más fotos y datos.'],
    cancel: ['¿Cómo cancelo o desisto del contrato?', 'Mediante «Cancelar suscripción», al pie de cada página y en tu cuenta, sin plazo de preaviso. Mantienes el acceso hasta el final del periodo pagado. En los 14 días siguientes al alta puedes desistir del contrato mediante «Desistir del contrato», también sin iniciar sesión.'],
  },
  insightA3: {
    title: 'Buscar gratis vs Bellen 18,50 €: qué pagas en Woonwekker',
    intro: 'Buscar y contactar con el anunciante es gratis. Bellen solo trata de velocidad y extras.',
    body: '<p>Muchos sitios de alquiler mezclan «crear una cuenta» con «pagar». En Woonwekker son cosas separadas, y contactar con un anunciante no pertenece a ninguna de las dos: siempre es gratis.</p>\n<p><strong>Gratis (Kijken).</strong> Navegas, filtras y guardas perfiles de búsqueda. Cada vivienda muestra la fuente y la fecha de la última comprobación. Con un clic abres el anuncio original en el sitio web donde aparece, y allí respondes directamente al anunciante.</p>\n<p><strong>Bellen: 1 día gratis, después precio total 18,50 € al mes.</strong> Bellen es una suscripción opcional para ganar velocidad y extras: alertas por correo inmediatas, filtros adicionales y prioridad en las notificaciones. Se renueva cada mes hasta que la canceles. Puedes cancelar siempre en línea mediante <a href="/opzeggen/">Cancelar suscripción</a>. Las nuevas suscripciones no están disponibles temporalmente.</p>\n<p><strong>Lo que Bellen no es.</strong> Woonwekker no es una agencia inmobiliaria ni un intermediario y no alquila viviendas. Bellen no da acceso a datos de contacto ni garantiza que consigas una vivienda. Las reglas están en las <a href="/voorwaarden/">condiciones generales</a>; precios y detalles en <a href="/prijzen/">precios</a>.</p>',
  },
};
