'use strict';
module.exports = {
  version: 'Versione 1.0, valida dall’8 ottobre 2026. Prevale il testo olandese; le traduzioni sono un aiuto.',
  voorwaarden: {
    title: 'Condizioni generali',
    meta: 'Condizioni generali di Woonwekker: servizio di ricerca e avvisi, non un’agenzia immobiliare né un intermediario. Abbonamento Bellen, giorno gratuito, prezzo, rinnovo e disdetta.',
    sections: [
      ['1. Chi siamo', 'Vorxeo (Woonwekker), iscritta alla Camera di Commercio olandese (KvK) con il numero 42108778, partita IVA NL005499683B86 («noi»). Woonwekker è una divisione di Vorxeo. Vorxeo: Keizersgracht 520H, 1017 EK Amsterdam, Nederland. +31 85 212 77 69. support@vorxeo.com.'],
      ['2. Che cos’è Woonwekker', 'Woonwekker è un servizio di ricerca e avvisi. Non siamo un’agenzia immobiliare né un intermediario e non affittiamo case. Gli annunci provengono da inserzioni pubbliche su altri siti; contatti direttamente l’inserzionista.', 'Non agiamo per conto di locatori o inquilini, non concludiamo contratti di locazione e non gestiamo domande di affitto. Per ogni casa mostriamo la fonte e la data in cui abbiamo controllato l’annuncio per l’ultima volta.'],
      ['3. Nessuna intermediazione, nessuna garanzia', 'Non addebitiamo commissioni di intermediazione. Non garantiamo che una casa sia ancora disponibile, che i dati di un annuncio siano corretti né che otterrai una casa. Verifica sempre prezzo, condizioni e disponibilità nell’annuncio originale e con l’inserzionista.'],
      ['4. Kijken (gratis)', 'Cercare, filtrare, preferiti, profili di ricerca e il link all’annuncio originale sono gratuiti, con o senza account. I dati di contatto e i link agli annunci non sono mai dietro un abbonamento a pagamento.'],
      ['5. Bellen (abbonamento a pagamento)', 'Bellen è un abbonamento facoltativo per velocità ed extra: avvisi e-mail immediati appena arriva una casa adatta, filtri aggiuntivi, priorità nelle notifiche, il kit di risposta, la checklist dei documenti e un compagno di ricerca. Bellen non dà accesso ai dati di contatto degli inserzionisti; quelli sono gratuiti per tutti.', 'Il prezzo totale è di 18,50 € al mese. Alla prima iscrizione il primo giorno è gratuito. Poi l’abbonamento si rinnova automaticamente ogni mese a tempo indeterminato e paghi 18,50 € al mese finché non disdici.', 'Al momento i nuovi abbonamenti sono temporaneamente non disponibili.'],
      ['6. Disdetta', 'Puoi disdire Bellen online in qualsiasi momento tramite «Disdici l’abbonamento», in fondo a ogni pagina o nel tuo account, senza preavviso. Dopo la disdetta non viene addebitato più nulla. Mantieni l’accesso fino alla fine del periodo già pagato. Se disdici durante il giorno gratuito, non paghi nulla.'],
      ['7. Diritto di recesso', 'Hai 14 giorni di ripensamento dalla conclusione dell’abbonamento. In quel periodo puoi recedere dal contratto senza indicarne il motivo tramite «Recedi dal contratto», anche senza accedere. Se hai chiesto che Bellen iniziasse subito, in caso di recesso paghi un importo proporzionale al periodo in cui Bellen è già stato fornito. La pagina Diritto di recesso contiene le informazioni complete e il modulo tipo.'],
      ['8. Rimborsi', 'Effettuiamo i rimborsi entro 14 giorni, con lo stesso mezzo di pagamento che hai usato. Vedi la politica di disdetta e rimborso.'],
      ['9. Annunci di terzi', 'Annunci, foto e testi appartengono agli inserzionisti e ai siti su cui compaiono. Rimandiamo all’annuncio originale. Rispondere, visitare e affittare avvengono al di fuori di Woonwekker, alle condizioni di quel sito e di quell’inserzionista.'],
      ['10. Responsabilità', 'Non siamo responsabili del contenuto di annunci di terzi né degli accordi che prendi con un inserzionista, salvo dolo o colpa grave da parte nostra. I tuoi diritti di legge come consumatore restano sempre validi. Non trasferire mai denaro basandoti solo su un annuncio.'],
      ['11. Modifiche', 'Possiamo modificare queste condizioni. Le modifiche che riguardano un abbonamento in corso vengono comunicate in anticipo; potrai allora disdire senza costi.'],
      ['12. Legge applicabile', 'Queste condizioni sono regolate dal diritto olandese. Come consumatore mantieni la tutela delle norme imperative del Paese in cui vivi.'],
    ],
  },
  privacy: {
    title: 'Informativa sulla privacy',
    meta: 'Informativa sulla privacy di Vorxeo (Woonwekker): quali dati tratta il sito, Google Ads dopo il consenso, e-mail tramite Resend, hosting e i tuoi diritti.',
    intro: 'Solo ciò che questo sito fa davvero con i dati.',
    sections: [
      ['Titolare', 'Woonwekker è il titolare del trattamento su questo sito. Numero KvK 42108778. Partita IVA NL005499683B86. Vorxeo: Keizersgracht 520H, 1017 EK Amsterdam, Nederland. +31 85 212 77 69. support@vorxeo.com.'],
      'KEEP:1',
      'KEEP:2',
      ['Pagamenti', 'Al momento non vengono elaborati nuovi pagamenti; i nuovi abbonamenti sono temporaneamente non disponibili. Per un abbonamento Bellen esistente il sito imposta un cookie firmato, ww_bellen, affinché il tuo accesso su questo dispositivo segua lo stato dell’abbonamento. I dati di pagamento di un abbonamento esistente sono trattati dal fornitore di pagamento con cui hai pagato. Non appena un fornitore di pagamento sarà di nuovo attivo, lo indicheremo qui prima che tu possa pagare.'],
      ['E-mail tramite Resend', 'L’e-mail di conferma all’iscrizione e le e-mail su abbonamento, disdetta o recesso vengono inviate tramite Resend, se sul server è presente una chiave API. Senza chiave quell’e-mail non viene inviata.'],
      ['Disdetta e recesso', 'Se usi il modulo «Disdici l’abbonamento» o «Recedi dal contratto», trattiamo il tuo nome, il tuo indirizzo e-mail, la data dell’ordine se la indichi e l’ora di ricezione. Lo facciamo per dare seguito alla tua richiesta e per poter dimostrare che è stata ricevuta in tempo (obbligo di legge).'],
      'KEEP:5',
      'KEEP:6',
      ['Hosting e foto', 'Il sito è ospitato su Vercel. Quando apri le pagine, Vercel riceve dati tecnici della richiesta, come indirizzo IP e tipo di browser, necessari per mostrare la pagina. Le foto delle case sono caricate direttamente dai server di immagini dei siti di origine, che ricevono anche il tuo indirizzo IP. Quando apri un annuncio originale, si applica l’informativa sulla privacy di quel sito.'],
      'KEEP:8',
    ],
  },
  terugbetaling: {
    title: 'Politica di disdetta e rimborso',
    meta: 'Disdetta e rimborso di Woonwekker Bellen: disdici online in qualsiasi momento, accesso fino alla fine del periodo pagato, recesso entro 14 giorni.',
    sections: [
      ['Disdetta', 'Puoi disdire Bellen online in qualsiasi momento tramite «Disdici l’abbonamento», senza preavviso e senza accedere. Dopo la disdetta non viene addebitato più nulla. Mantieni l’accesso fino alla fine del periodo già pagato; per quel periodo non è previsto un rimborso parziale, salvo recesso entro il periodo di ripensamento.'],
      ['Giorno gratuito', 'Se disdici durante il primo giorno gratuito, non paghi nulla.'],
      ['Recesso entro 14 giorni', 'Se recedi entro 14 giorni dalla conclusione dell’abbonamento, ti rimborsiamo tutto ciò che hai pagato. Se hai chiesto che Bellen iniziasse subito, tratteniamo un importo proporzionale al periodo in cui Bellen è già stato fornito.'],
      ['Come e quando', 'Rimborsiamo entro 14 giorni dal ricevimento del tuo recesso, con lo stesso mezzo di pagamento che hai usato, salvo che tu accetti espressamente altrimenti. Il rimborso non ti costa nulla.'],
      ['Addebito non dovuto', 'Se dopo la disdetta o il recesso viene comunque addebitato qualcosa, te lo rimborsiamo per intero.'],
    ],
  },
  herroeping: {
    title: 'Diritto di recesso',
    meta: 'Diritto di recesso per Woonwekker Bellen: 14 giorni, modulo tipo di recesso e il pulsante Recedi dal contratto.',
    sections: [
      ['Diritto di recesso', 'Hai il diritto di recedere dal contratto Bellen entro 14 giorni senza indicarne le ragioni. Il periodo di recesso scade dopo 14 giorni dal giorno della conclusione del contratto.'],
      ['Come recedere', 'Usa il pulsante «Recedi dal contratto» qui sotto; non è necessario accedere. Puoi anche usare il modulo tipo o inviare un’altra dichiarazione esplicita, ma non è obbligatorio. Per rispettare il termine basta inviare la dichiarazione prima che siano trascorsi i 14 giorni.'],
      ['Effetti del recesso', 'Se recedi, ti rimborseremo tutti i pagamenti effettuati per Bellen senza indebito ritardo e comunque entro 14 giorni dal giorno in cui riceviamo il tuo recesso. Useremo lo stesso mezzo di pagamento che hai usato, salvo che tu abbia espressamente convenuto altrimenti; il rimborso non ti costa nulla.', 'Se hai chiesto che Bellen iniziasse durante il periodo di recesso, paghi un importo proporzionale a quanto fornito fino al momento in cui ci comunichi il recesso, rispetto all’esecuzione completa del contratto.'],
      ['Conferma di ricezione', 'Dopo l’invio vedi subito una conferma con data, ora e riferimento. Conservala. Se l’invio di e-mail è configurato, ti inviamo la conferma anche per e-mail.'],
    ],
    modelTitle: 'Modulo tipo di recesso',
    modelNote: '(compilare e restituire il presente modulo solo se si desidera recedere dal contratto)',
    modelLines: [
      'Destinatario: Vorxeo (Woonwekker), numero KvK 42108778. Puoi inviarlo tramite il modulo «Recedi dal contratto» in questa pagina. Vorxeo: Keizersgracht 520H, 1017 EK Amsterdam, Nederland. +31 85 212 77 69. support@vorxeo.com.',
      'Con la presente io/noi* notifichiamo il recesso dal mio/nostro* contratto per la prestazione del seguente servizio: Woonwekker Bellen',
      'Ordinato il* [data dell’ordine]',
      '[Nome del/dei consumatore(i)]',
      '[Indirizzo del/dei consumatore(i)]',
      '[Firma del/dei consumatore(i)] (solo se il presente modulo è notificato in versione cartacea)',
      '[Data (GG-MM-AAAA)]',
    ],
    modelFoot: '* Cancellare la dicitura inutile.',
    formTitle: 'Recedi dal contratto',
    formIntro: 'Inserisci il nome e l’indirizzo e-mail con cui ti sei iscritto. Non è necessario accedere.',
  },
  opzeggen: {
    title: 'Disdici l’abbonamento',
    meta: 'Disdici online il tuo abbonamento Woonwekker Bellen, senza preavviso e senza accedere.',
    paragraphs: [
      'Qui disdici il tuo abbonamento Bellen. Non c’è preavviso.',
      'Dopo la disdetta non viene addebitato più nulla. Mantieni l’accesso fino alla fine del periodo già pagato. Se disdici durante il giorno gratuito, non paghi nulla.',
      'Inserisci il nome e l’indirizzo e-mail con cui ti sei iscritto e clicca su «Disdici l’abbonamento». Non è necessario accedere. Vedi subito una conferma.',
    ],
    withdrawHint: 'Vuoi recedere dal contratto entro 14 giorni dall’iscrizione e riavere i tuoi soldi? Usa',
  },
  faqNew: {
    what: ['Che cos’è Woonwekker?', 'Woonwekker è un servizio di ricerca e avvisi. Non siamo un’agenzia immobiliare né un intermediario e non affittiamo case. Gli annunci provengono da inserzioni pubbliche su altri siti; contatti direttamente l’inserzionista.'],
    sources: ['Da dove vengono gli annunci?', 'Da inserzioni pubbliche su altri siti: piattaforme immobiliari esterne. Ogni casa mostra la fonte e la data in cui abbiamo controllato l’annuncio per l’ultima volta.'],
    fresh: ['Le case sono ancora disponibili?', 'Non possiamo saperlo con certezza. Non mostriamo annunci che sulla fonte risultano «in trattativa» o non disponibili, e nascondiamo gli annunci che non controlliamo da più di {days} giorni. Verifica sempre lo stato attuale nell’annuncio originale.'],
    contact: ['Come contatto l’inserzionista o prenoto una visita?', 'Apri una casa e scegli «Vedi l’annuncio originale». Rispondi direttamente all’inserzionista, su quel sito. Su Woonwekker è gratis. Il sito di origine ha le sue condizioni. Le piattaforme esterne possono richiedere un account o un pagamento per rispondere. Questo è indipendente da Woonwekker.'],
    pay: ['Devo pagare per cercare?', 'No. Cercare, filtrare e il link all’annuncio originale sono gratuiti. Bellen è un abbonamento facoltativo per avvisi più rapidi, filtri aggiuntivi e priorità nelle notifiche: 1 giorno gratis, poi prezzo totale 18,50 € al mese, con rinnovo automatico finché non disdici. I dati di contatto e i link agli annunci non sono mai dietro Bellen. I nuovi abbonamenti sono temporaneamente non disponibili.'],
    alerts: ['Ricevo avvisi per le nuove case?', 'Imposti profili di ricerca e avvisi e-mail in Account. Con Kijken ricevi al massimo 3 avvisi e-mail a settimana; con Bellen, avvisi e-mail immediati e priorità nelle notifiche.'],
    photos: ['Perché una casa ha solo poche foto?', 'Mostriamo le foto dell’annuncio originale, così come le fornisce il sito di origine. Altre foto e dati si trovano nell’annuncio originale.'],
    cancel: ['Come disdico o recedo dal contratto?', 'Tramite «Disdici l’abbonamento», in fondo a ogni pagina e nel tuo account, senza preavviso. Mantieni l’accesso fino alla fine del periodo pagato. Entro 14 giorni dall’iscrizione puoi recedere dal contratto tramite «Recedi dal contratto», anche senza accedere.'],
  },
  insightA3: {
    title: 'Ricerca gratuita vs Bellen 18,50 €: cosa paghi su Woonwekker',
    intro: 'Cercare e contattare l’inserzionista è gratis. Bellen riguarda solo velocità ed extra.',
    body: '<p>Molti siti di affitti confondono «creare un account» con «pagare». Su Woonwekker sono cose separate, e contattare un inserzionista non rientra in nessuna delle due: è sempre gratis.</p>\n<p><strong>Gratis (Kijken).</strong> Sfogli, filtri e salvi profili di ricerca. Ogni casa mostra la fonte e la data dell’ultimo controllo. Con un clic apri l’annuncio originale sul sito dove è pubblicato, e lì rispondi direttamente all’inserzionista.</p>\n<p><strong>Bellen: 1 giorno gratis, poi prezzo totale 18,50 € al mese.</strong> Bellen è un abbonamento facoltativo per velocità ed extra: avvisi e-mail immediati, filtri aggiuntivi e priorità nelle notifiche. Si rinnova ogni mese finché non disdici. Puoi sempre disdire online tramite <a href="/opzeggen/">Disdici l’abbonamento</a>. I nuovi abbonamenti sono temporaneamente non disponibili.</p>\n<p><strong>Cosa non è Bellen.</strong> Woonwekker non è un’agenzia immobiliare né un intermediario e non affitta case. Bellen non dà accesso ai dati di contatto e non garantisce che otterrai una casa. Le regole sono nelle <a href="/voorwaarden/">condizioni generali</a>; prezzi e dettagli in <a href="/prijzen/">prezzi</a>.</p>',
  },
};
