'use strict';
// Dutch: authoritative version of every legal text.
module.exports = {
  version: 'Versie 1.0, geldig vanaf 8 oktober 2026. De Nederlandse tekst is leidend; vertalingen zijn een hulpmiddel.',
  voorwaarden: {
    title: 'Algemene voorwaarden',
    meta: 'Algemene voorwaarden van Woonwekker: zoek- en alertdienst, geen makelaar of bemiddelaar. Abonnement Bellen, proefdag, prijs, verlenging en opzeggen.',
    sections: [
      ['1. Wie wij zijn', 'Vorxeo (Woonwekker), ingeschreven bij de Kamer van Koophandel onder nummer 42108778, btw-nummer NL005499683B86 (‘wij’). Woonwekker is een bedrijfsonderdeel van Vorxeo.'],
      ['2. Wat Woonwekker is', 'Woonwekker is een zoek- en alertdienst. Wij zijn geen makelaar of bemiddelaar en verhuren geen woningen. Het aanbod komt van openbare advertenties op andere websites; je neemt rechtstreeks contact op met de aanbieder.', 'Wij werken niet in opdracht van verhuurders of huurders, sluiten geen huurovereenkomsten en behandelen geen huuraanvragen. Bij elke woning tonen we de bron en de datum waarop we de advertentie het laatst hebben gecontroleerd.'],
      ['3. Geen bemiddeling, geen garantie', 'Wij rekenen geen bemiddelingskosten. Wij garanderen niet dat een woning nog beschikbaar is, dat de gegevens in een advertentie kloppen of dat je een woning krijgt. Controleer prijs, voorwaarden en beschikbaarheid altijd in de originele advertentie en bij de aanbieder.'],
      ['4. Kijken (gratis)', 'Zoeken, filteren, favorieten, zoekprofielen en de link naar de originele advertentie zijn gratis, met of zonder account. Contactgegevens en links naar advertenties staan nooit achter een betaald abonnement.'],
      ['5. Bellen (betaald abonnement)', 'Bellen is een optioneel abonnement voor snelheid en extra’s: directe e-mailalerts zodra een passende woning binnenkomt, extra filters, voorrang bij meldingen, de reactie-kit, de documentenchecklist en één zoekgenoot. Bellen geeft geen toegang tot contactgegevens van aanbieders; die zijn voor iedereen gratis.', 'De totaalprijs is €18,50 per maand. Bij een eerste aanmelding is de eerste dag gratis. Daarna wordt het abonnement elke maand automatisch verlengd voor onbepaalde tijd en betaal je €18,50 per maand, tot je opzegt.', 'Nieuwe abonnementen zijn op dit moment tijdelijk niet beschikbaar.'],
      ['6. Opzeggen', 'Je kunt Bellen altijd online opzeggen via ‘Abonnement opzeggen’ onderaan elke pagina of in je account, zonder opzegtermijn. Na opzegging wordt er niets meer afgeschreven. Je houdt toegang tot het einde van de periode waarvoor je al hebt betaald. Zeg je op tijdens de gratis dag, dan betaal je niets.'],
      ['7. Herroepingsrecht', 'Je hebt 14 dagen bedenktijd vanaf het sluiten van het abonnement. In die periode kun je de overeenkomst zonder opgave van redenen ontbinden via ‘Overeenkomst ontbinden’, ook zonder in te loggen. Heb je gevraagd om Bellen direct te laten starten, dan betaal je bij ontbinding een evenredig bedrag voor de periode waarin Bellen al is geleverd. Op de pagina Herroepingsrecht staan de volledige informatie en het modelformulier.'],
      ['8. Terugbetaling', 'Terugbetalingen doen we binnen 14 dagen, met hetzelfde betaalmiddel als waarmee je hebt betaald. Zie het opzeg- en terugbetalingsbeleid.'],
      ['9. Advertenties van anderen', 'Advertenties, foto’s en teksten zijn van de aanbieders en van de websites waarop ze staan. Wij linken naar de originele advertentie. Reageren, bezichtigen en huren gaan buiten Woonwekker om, onder de voorwaarden van die website en die aanbieder.'],
      ['10. Aansprakelijkheid', 'Wij zijn niet aansprakelijk voor de inhoud van advertenties van anderen of voor afspraken die je met een aanbieder maakt, behalve bij opzet of bewuste roekeloosheid van onze kant. Je wettelijke rechten als consument blijven altijd gelden. Maak nooit geld over op basis van alleen een advertentie.'],
      ['11. Wijzigingen', 'Wij kunnen deze voorwaarden wijzigen. Wijzigingen die een lopend abonnement raken, melden we vooraf; je kunt dan kosteloos opzeggen.'],
      ['12. Toepasselijk recht', 'Op deze voorwaarden is Nederlands recht van toepassing. Als consument houd je de bescherming van de dwingende regels van het land waar je woont.'],
    ],
  },
  privacy: {
    title: 'Privacyverklaring',
    meta: 'Privacyverklaring van Vorxeo (Woonwekker): welke gegevens de site verwerkt, Google Ads na toestemming, e-mail via Resend, hosting en je rechten.',
    intro: 'Alleen wat deze website echt doet met gegevens.',
    sections: [
      ['Verantwoordelijke', 'Woonwekker is de verantwoordelijke voor verwerkingen op deze website. KvK-nummer 42108778. Btw-nummer NL005499683B86.'],
      'KEEP:1',
      'KEEP:2',
      ['Betalingen', 'Op dit moment worden er geen nieuwe betalingen verwerkt; nieuwe abonnementen zijn tijdelijk niet beschikbaar. Voor een bestaand Bellen-abonnement zet de site een ondertekende cookie, ww_bellen, zodat je toegang op dit apparaat de status van je abonnement volgt. De betaalgegevens van een bestaand abonnement worden verwerkt door de betaaldienstverlener waarmee je hebt betaald. Zodra er weer een betaaldienstverlener actief is, noemen we die hier voordat je kunt betalen.'],
      ['E-mail via Resend', 'De bevestigingsmail bij aanmelden en e-mails over je abonnement, opzegging of ontbinding gaan via Resend, als er een API-sleutel op de server staat. Zonder sleutel wordt die mail niet verstuurd.'],
      ['Opzeggen en ontbinden', 'Als je het formulier ‘Abonnement opzeggen’ of ‘Overeenkomst ontbinden’ gebruikt, verwerken we je naam, je e-mailadres, de datum van bestelling als je die invult, en het tijdstip van ontvangst. Dat doen we om je verzoek uit te voeren en om te kunnen aantonen dat het op tijd is ontvangen (wettelijke verplichting).'],
      'KEEP:5',
      'KEEP:6',
      ['Hosting en foto’s', 'De site draait bij Vercel. Bij het openen van pagina’s ontvangt Vercel technische verzoekgegevens, zoals IP-adres en browsertype, die nodig zijn om de pagina te tonen. Foto’s van woningen worden rechtstreeks geladen van de beeldservers van de bronwebsites; die ontvangen daarbij ook je IP-adres. Als je een originele advertentie opent, geldt het privacybeleid van die website.'],
      'KEEP:8',
    ],
  },
  terugbetaling: {
    title: 'Opzeg- en terugbetalingsbeleid',
    meta: 'Opzeggen en terugbetalen bij Woonwekker Bellen: altijd online opzeggen, toegang tot het einde van de betaalde periode, ontbinden binnen 14 dagen.',
    sections: [
      ['Opzeggen', 'Je kunt Bellen altijd online opzeggen via ‘Abonnement opzeggen’, zonder opzegtermijn en zonder in te loggen. Na opzegging wordt er niets meer afgeschreven. Je houdt toegang tot het einde van de periode waarvoor je al hebt betaald; voor die periode volgt geen gedeeltelijke terugbetaling, behalve bij ontbinding binnen de bedenktijd.'],
      ['Gratis dag', 'Zeg je op tijdens de gratis eerste dag, dan betaal je niets.'],
      ['Ontbinden binnen 14 dagen', 'Ontbind je binnen 14 dagen na het sluiten van het abonnement, dan betalen we alles terug wat je hebt betaald. Heb je gevraagd om Bellen direct te laten starten, dan houden we een evenredig bedrag in voor de periode waarin Bellen al is geleverd.'],
      ['Hoe en wanneer', 'We betalen terug binnen 14 dagen nadat we je ontbinding hebben ontvangen, met hetzelfde betaalmiddel als waarmee je hebt betaald, tenzij je uitdrukkelijk met iets anders instemt. Aan de terugbetaling zijn voor jou geen kosten verbonden.'],
      ['Onterechte afschrijving', 'Is er na je opzegging of ontbinding toch iets afgeschreven, dan betalen we dat volledig terug.'],
    ],
  },
  herroeping: {
    title: 'Herroepingsrecht',
    meta: 'Herroepingsrecht bij Woonwekker Bellen: 14 dagen bedenktijd, modelformulier voor herroeping en de knop Overeenkomst ontbinden.',
    sections: [
      ['Herroepingsrecht', 'Je hebt het recht om de overeenkomst voor Bellen binnen 14 dagen zonder opgave van redenen te herroepen (ontbinden). De herroepingstermijn verstrijkt 14 dagen na de dag waarop de overeenkomst is gesloten.'],
      ['Hoe je herroept', 'Gebruik de knop ‘Overeenkomst ontbinden’ hieronder; inloggen is niet nodig. Je mag ook het modelformulier gebruiken of op een andere manier een ondubbelzinnige verklaring sturen, maar dat is niet verplicht. Om de termijn te halen is het genoeg dat je je verklaring verstuurt voordat de 14 dagen voorbij zijn.'],
      ['Gevolgen van herroeping', 'Als je herroept, betalen we alle betalingen die je voor Bellen hebt gedaan onverwijld terug, en in ieder geval binnen 14 dagen nadat we je herroeping hebben ontvangen. We gebruiken hetzelfde betaalmiddel als waarmee je hebt betaald, tenzij je uitdrukkelijk met iets anders instemt; aan de terugbetaling zijn voor jou geen kosten verbonden.', 'Heb je gevraagd om Bellen te laten beginnen tijdens de herroepingstermijn, dan betaal je een bedrag dat evenredig is aan wat al is geleverd op het moment dat je ons laat weten dat je herroept, vergeleken met de volledige uitvoering van de overeenkomst.'],
      ['Ontvangstbevestiging', 'Na het versturen zie je direct een bevestiging met datum, tijd en referentie. Bewaar die. Als verzending van e-mail is ingesteld, sturen we de bevestiging ook per e-mail.'],
    ],
    modelTitle: 'Modelformulier voor herroeping',
    modelNote: '(dit formulier alleen invullen en terugzenden wanneer u de overeenkomst wilt herroepen)',
    modelLines: [
      'Aan: Vorxeo (Woonwekker), KvK-nummer 42108778. Indienen kan via het formulier ‘Overeenkomst ontbinden’ op deze pagina.',
      'Ik/Wij* deel/delen* u hierbij mede, dat ik/wij* onze overeenkomst betreffende de verrichting van de volgende dienst: Woonwekker Bellen, herroep/herroepen*',
      'Besteld op* [datum bestelling]',
      '[Naam consument(en)]',
      '[Adres consument(en)]',
      '[Handtekening consument(en)] (alleen wanneer dit formulier op papier wordt ingediend)',
      '[Datum (DD-MM-JJJJ)]',
    ],
    modelFoot: '* Doorhalen wat niet van toepassing is of invullen wat van toepassing is.',
    formTitle: 'Overeenkomst ontbinden',
    formIntro: 'Vul de naam en het e-mailadres in waarmee je je aanmeldde. Inloggen is niet nodig.',
  },
  opzeggen: {
    title: 'Abonnement opzeggen',
    meta: 'Je Woonwekker Bellen-abonnement online opzeggen, zonder opzegtermijn en zonder inloggen.',
    paragraphs: [
      'Hier zeg je je Bellen-abonnement op. Er is geen opzegtermijn.',
      'Na opzegging wordt er niets meer afgeschreven. Je houdt toegang tot het einde van de periode waarvoor je al hebt betaald. Zeg je op tijdens de gratis dag, dan betaal je niets.',
      'Vul de naam en het e-mailadres in waarmee je je aanmeldde en klik op ‘Abonnement opzeggen’. Inloggen is niet nodig. Je ziet direct een bevestiging.',
    ],
    withdrawHint: 'Wil je binnen 14 dagen na aanmelding de overeenkomst ontbinden en je geld terugkrijgen? Gebruik dan',
  },
  faqNew: {
    what: ['Wat is Woonwekker?', 'Woonwekker is een zoek- en alertdienst. Wij zijn geen makelaar of bemiddelaar en verhuren geen woningen. Het aanbod komt van openbare advertenties op andere websites; je neemt rechtstreeks contact op met de aanbieder.'],
    sources: ['Waar komt het aanbod vandaan?', 'Uit openbare advertenties op andere websites: externe woningplatforms. Bij elke woning staan de bron en de datum waarop we de advertentie het laatst hebben gecontroleerd.'],
    fresh: ['Zijn de woningen nog beschikbaar?', 'Dat weten we niet zeker. Advertenties die bij de bron ‘in onderhandeling’ of niet beschikbaar zijn, tonen we niet, en advertenties die we langer dan {days} dagen niet hebben gecontroleerd, verbergen we. Controleer de actuele status altijd in de originele advertentie.'],
    contact: ['Hoe neem ik contact op of plan ik een bezichtiging?', 'Open een woning en kies ‘Bekijk de originele advertentie’. Je reageert rechtstreeks bij de aanbieder, op die website. Dat is gratis bij Woonwekker. De bronwebsite heeft eigen voorwaarden. Externe woningplatforms kunnen een eigen account of betaling vereisen om te reageren. Dit staat los van Woonwekker.'],
    pay: ['Moet ik betalen om te zoeken?', 'Nee. Zoeken, filteren en de link naar de originele advertentie zijn gratis. Bellen is een optioneel abonnement voor snellere alerts, extra filters en voorrang bij meldingen: 1 dag gratis, daarna totaalprijs €18,50 per maand, automatisch verlengd tot je opzegt. Contactgegevens en links naar advertenties zitten nooit achter Bellen. Nieuwe abonnementen zijn tijdelijk niet beschikbaar.'],
    alerts: ['Krijg ik meldingen van nieuwe woningen?', 'Je stelt zoekprofielen en e-mailmeldingen in onder Account. Met Kijken ontvang je maximaal 3 e-mailalerts per week; met Bellen directe e-mailalerts en voorrang bij meldingen.'],
    photos: ['Waarom heeft een woning maar enkele foto’s?', 'We tonen de foto’s uit de originele advertentie, zoals de bronwebsite ze aanbiedt. Meer foto’s en gegevens vind je in de originele advertentie.'],
    cancel: ['Hoe zeg ik op of ontbind ik de overeenkomst?', 'Via ‘Abonnement opzeggen’ onderaan elke pagina en in je account, zonder opzegtermijn. Je houdt toegang tot het einde van de betaalde periode. Binnen 14 dagen na aanmelding kun je de overeenkomst ontbinden via ‘Overeenkomst ontbinden’, ook zonder in te loggen.'],
  },
  insightA3: {
    title: 'Gratis zoeken vs Bellen €18,50: waar je voor betaalt op Woonwekker',
    intro: 'Zoeken en contact met de aanbieder zijn gratis. Bellen gaat alleen over snelheid en extra’s.',
    body: '<p>Veel huursites vermengen “account aanmaken” met “betalen”. Op Woonwekker zijn die twee los van elkaar, en contact met een aanbieder hoort bij geen van beide: dat is altijd gratis.</p>\n<p><strong>Gratis (Kijken).</strong> Je bladert, filtert en bewaart zoekprofielen. Bij elke woning staan de bron en de datum van de laatste controle. Met één klik open je de originele advertentie op de website waar die staat, en daar reageer je rechtstreeks bij de aanbieder.</p>\n<p><strong>Bellen: 1 dag gratis, daarna totaalprijs €18,50 per maand.</strong> Bellen is een optioneel abonnement voor snelheid en extra’s: directe e-mailalerts, extra filters en voorrang bij meldingen. Het abonnement wordt elke maand verlengd tot je opzegt. Opzeggen kan altijd online via <a href="/opzeggen/">Abonnement opzeggen</a>. Nieuwe abonnementen zijn tijdelijk niet beschikbaar.</p>\n<p><strong>Wat Bellen niet is.</strong> Woonwekker is geen makelaar of bemiddelaar en verhuurt geen woningen. Bellen is geen toegang tot contactgegevens en geen garantie dat je een woning krijgt. De voorwaarden staan in de <a href="/voorwaarden/">algemene voorwaarden</a>; prijzen en details staan op <a href="/prijzen/">prijzen</a>.</p>',
  },
};
