'use strict';
module.exports = {
  version: 'Wersja 1.0, obowiązuje od 8 października 2026 r. Wiążący jest tekst niderlandzki; tłumaczenia mają charakter pomocniczy.',
  voorwaarden: {
    title: 'Ogólne warunki',
    meta: 'Ogólne warunki Woonwekker: serwis wyszukiwania i powiadomień, nie agencja nieruchomości ani pośrednik. Subskrypcja Bellen, darmowy dzień, cena, odnowienie i rezygnacja.',
    sections: [
      ['1. Kim jesteśmy', 'Vorxeo (Woonwekker), wpisany do niderlandzkiej Izby Handlowej (KvK) pod numerem 42108778, numer VAT NL005499683B86 („my”). Woonwekker jest częścią firmy Vorxeo.'],
      ['2. Czym jest Woonwekker', 'Woonwekker to serwis wyszukiwania i powiadomień. Nie jesteśmy agencją nieruchomości ani pośrednikiem i nie wynajmujemy mieszkań. Oferty pochodzą z publicznych ogłoszeń na innych stronach; kontaktujesz się bezpośrednio z ogłoszeniodawcą.', 'Nie działamy na zlecenie wynajmujących ani najemców, nie zawieramy umów najmu i nie obsługujemy wniosków o najem. Przy każdym mieszkaniu pokazujemy źródło i datę ostatniego sprawdzenia ogłoszenia.'],
      ['3. Bez pośrednictwa, bez gwarancji', 'Nie pobieramy prowizji za pośrednictwo. Nie gwarantujemy, że mieszkanie jest nadal dostępne, że dane w ogłoszeniu są poprawne ani że otrzymasz mieszkanie. Zawsze sprawdzaj cenę, warunki i dostępność w oryginalnym ogłoszeniu i u ogłoszeniodawcy.'],
      ['4. Kijken (bezpłatnie)', 'Wyszukiwanie, filtrowanie, ulubione, profile wyszukiwania i link do oryginalnego ogłoszenia są bezpłatne, z kontem lub bez. Dane kontaktowe i linki do ogłoszeń nigdy nie są ukryte za płatną subskrypcją.'],
      ['5. Bellen (płatna subskrypcja)', 'Bellen to opcjonalna subskrypcja dla szybkości i dodatków: natychmiastowe powiadomienia e-mail, gdy tylko pojawi się pasujące mieszkanie, dodatkowe filtry, pierwszeństwo powiadomień, zestaw do odpowiedzi, lista dokumentów i jeden współposzukujący. Bellen nie daje dostępu do danych kontaktowych ogłoszeniodawców; są one bezpłatne dla wszystkich.', 'Cena całkowita wynosi 18,50 € miesięcznie. Przy pierwszej rejestracji pierwszy dzień jest bezpłatny. Następnie subskrypcja odnawia się automatycznie co miesiąc na czas nieokreślony i płacisz 18,50 € miesięcznie, dopóki nie zrezygnujesz.', 'Nowe subskrypcje są obecnie tymczasowo niedostępne.'],
      ['6. Rezygnacja', 'Możesz zrezygnować z Bellen online w każdej chwili przez „Anuluj subskrypcję” na dole każdej strony lub na swoim koncie, bez okresu wypowiedzenia. Po rezygnacji nic więcej nie jest pobierane. Zachowujesz dostęp do końca okresu, za który już zapłaciłeś. Jeśli zrezygnujesz w darmowym dniu, nic nie płacisz.'],
      ['7. Prawo odstąpienia od umowy', 'Masz 14 dni na odstąpienie od umowy od dnia zawarcia subskrypcji. W tym czasie możesz odstąpić od umowy bez podania przyczyny przez „Odstąp od umowy”, także bez logowania. Jeśli poprosiłeś o natychmiastowe rozpoczęcie Bellen, przy odstąpieniu płacisz kwotę proporcjonalną do okresu, w którym Bellen był już świadczony. Pełne informacje i wzór formularza znajdziesz na stronie Prawo odstąpienia od umowy.'],
      ['8. Zwroty', 'Zwrotów dokonujemy w ciągu 14 dni, tym samym sposobem płatności, którego użyłeś. Zobacz zasady rezygnacji i zwrotów.'],
      ['9. Ogłoszenia innych', 'Ogłoszenia, zdjęcia i teksty należą do ogłoszeniodawców i stron, na których się znajdują. Linkujemy do oryginalnego ogłoszenia. Odpowiadanie, oglądanie i wynajem odbywają się poza Woonwekker, na warunkach tej strony i tego ogłoszeniodawcy.'],
      ['10. Odpowiedzialność', 'Nie odpowiadamy za treść ogłoszeń innych ani za ustalenia, które zawierasz z ogłoszeniodawcą, z wyjątkiem winy umyślnej lub rażącego niedbalstwa z naszej strony. Twoje ustawowe prawa konsumenta zawsze obowiązują. Nigdy nie przelewaj pieniędzy wyłącznie na podstawie ogłoszenia.'],
      ['11. Zmiany', 'Możemy zmienić te warunki. Zmiany dotyczące trwającej subskrypcji ogłaszamy z wyprzedzeniem; możesz wtedy bezpłatnie zrezygnować.'],
      ['12. Prawo właściwe', 'Do tych warunków stosuje się prawo niderlandzkie. Jako konsument zachowujesz ochronę bezwzględnie obowiązujących przepisów kraju, w którym mieszkasz.'],
    ],
  },
  privacy: {
    title: 'Polityka prywatności',
    meta: 'Polityka prywatności Vorxeo (Woonwekker): jakie dane przetwarza strona, Google Ads po wyrażeniu zgody, e-mail przez Resend, hosting i Twoje prawa.',
    intro: 'Tylko to, co ta strona naprawdę robi z danymi.',
    sections: [
      ['Administrator', 'Woonwekker jest administratorem danych przetwarzanych na tej stronie. Numer KvK 42108778. Numer VAT NL005499683B86.'],
      'KEEP:1',
      'KEEP:2',
      ['Płatności', 'Obecnie nie są przetwarzane nowe płatności; nowe subskrypcje są tymczasowo niedostępne. Dla istniejącej subskrypcji Bellen strona ustawia podpisany plik cookie ww_bellen, aby Twój dostęp na tym urządzeniu odpowiadał statusowi subskrypcji. Dane płatnicze istniejącej subskrypcji przetwarza dostawca płatności, przez którego zapłaciłeś. Gdy dostawca płatności znów będzie aktywny, wskażemy go tutaj, zanim będziesz mógł zapłacić.'],
      ['E-mail przez Resend', 'E-mail potwierdzający przy rejestracji oraz e-maile dotyczące subskrypcji, rezygnacji lub odstąpienia są wysyłane przez Resend, jeśli na serwerze jest klucz API. Bez klucza ten e-mail nie jest wysyłany.'],
      ['Rezygnacja i odstąpienie', 'Jeśli korzystasz z formularza „Anuluj subskrypcję” lub „Odstąp od umowy”, przetwarzamy Twoje imię i nazwisko, adres e-mail, datę zamówienia, jeśli ją podasz, oraz czas otrzymania. Robimy to, aby wykonać Twoje żądanie i móc wykazać, że zostało otrzymane w terminie (obowiązek prawny).'],
      'KEEP:5',
      'KEEP:6',
      ['Hosting i zdjęcia', 'Strona działa na Vercel. Przy otwieraniu stron Vercel otrzymuje techniczne dane żądania, takie jak adres IP i typ przeglądarki, potrzebne do wyświetlenia strony. Zdjęcia mieszkań są ładowane bezpośrednio z serwerów obrazów stron źródłowych, które również otrzymują Twój adres IP. Po otwarciu oryginalnego ogłoszenia obowiązuje polityka prywatności tej strony.'],
      'KEEP:8',
    ],
  },
  terugbetaling: {
    title: 'Zasady rezygnacji i zwrotów',
    meta: 'Rezygnacja i zwroty w Woonwekker Bellen: rezygnacja online w każdej chwili, dostęp do końca opłaconego okresu, odstąpienie w ciągu 14 dni.',
    sections: [
      ['Rezygnacja', 'Możesz zrezygnować z Bellen online w każdej chwili przez „Anuluj subskrypcję”, bez okresu wypowiedzenia i bez logowania. Po rezygnacji nic więcej nie jest pobierane. Zachowujesz dostęp do końca okresu, za który już zapłaciłeś; za ten okres nie ma częściowego zwrotu, chyba że odstąpisz od umowy w terminie na odstąpienie.'],
      ['Darmowy dzień', 'Jeśli zrezygnujesz w pierwszym, darmowym dniu, nic nie płacisz.'],
      ['Odstąpienie w ciągu 14 dni', 'Jeśli odstąpisz od umowy w ciągu 14 dni od zawarcia subskrypcji, zwrócimy wszystko, co zapłaciłeś. Jeśli poprosiłeś o natychmiastowe rozpoczęcie Bellen, zatrzymamy kwotę proporcjonalną do okresu, w którym Bellen był już świadczony.'],
      ['Jak i kiedy', 'Zwrotu dokonujemy w ciągu 14 dni od otrzymania Twojego odstąpienia, tym samym sposobem płatności, którego użyłeś, chyba że wyraźnie zgodzisz się na inny. Zwrot nic Cię nie kosztuje.'],
      ['Nienależne obciążenie', 'Jeśli po rezygnacji lub odstąpieniu mimo to coś zostanie pobrane, zwrócimy to w całości.'],
    ],
  },
  herroeping: {
    title: 'Prawo odstąpienia od umowy',
    meta: 'Prawo odstąpienia od umowy w Woonwekker Bellen: 14 dni, wzór formularza odstąpienia i przycisk Odstąp od umowy.',
    sections: [
      ['Prawo odstąpienia od umowy', 'Masz prawo odstąpić od umowy Bellen w terminie 14 dni bez podania jakiejkolwiek przyczyny. Termin do odstąpienia od umowy wygasa po upływie 14 dni od dnia zawarcia umowy.'],
      ['Jak odstąpić', 'Użyj przycisku „Odstąp od umowy” poniżej; logowanie nie jest potrzebne. Możesz też skorzystać ze wzoru formularza lub wysłać inne jednoznaczne oświadczenie, ale nie jest to obowiązkowe. Aby zachować termin, wystarczy wysłać oświadczenie przed upływem 14 dni.'],
      ['Skutki odstąpienia od umowy', 'W przypadku odstąpienia zwrócimy wszystkie płatności dokonane za Bellen niezwłocznie, a w każdym razie nie później niż 14 dni od dnia otrzymania Twojego odstąpienia. Użyjemy tego samego sposobu płatności, którego użyłeś, chyba że wyraźnie zgodzisz się na inny; zwrot nic Cię nie kosztuje.', 'Jeśli zażądałeś rozpoczęcia Bellen przed upływem terminu do odstąpienia, zapłacisz kwotę proporcjonalną do zakresu świadczeń spełnionych do chwili poinformowania nas o odstąpieniu, w stosunku do pełnego zakresu umowy.'],
      ['Potwierdzenie otrzymania', 'Po wysłaniu od razu zobaczysz potwierdzenie z datą, godziną i numerem referencyjnym. Zachowaj je. Jeśli wysyłanie e-maili jest skonfigurowane, wyślemy potwierdzenie także e-mailem.'],
    ],
    modelTitle: 'Wzór formularza odstąpienia od umowy',
    modelNote: '(formularz ten należy wypełnić i odesłać tylko w przypadku chęci odstąpienia od umowy)',
    modelLines: [
      'Adresat: Vorxeo (Woonwekker), numer KvK 42108778. Można go złożyć przez formularz „Odstąp od umowy” na tej stronie.',
      'Ja/My(*) niniejszym informuję/informujemy(*) o moim/naszym odstąpieniu od umowy o świadczenie następującej usługi: Woonwekker Bellen',
      'Data zawarcia umowy(*) [data zamówienia]',
      '[Imię i nazwisko konsumenta(-ów)]',
      '[Adres konsumenta(-ów)]',
      '[Podpis konsumenta(-ów)] (tylko jeżeli formularz jest przesyłany w wersji papierowej)',
      '[Data (DD-MM-RRRR)]',
    ],
    modelFoot: '(*) Niepotrzebne skreślić.',
    formTitle: 'Odstąp od umowy',
    formIntro: 'Podaj imię i nazwisko oraz adres e-mail, których użyłeś przy rejestracji. Logowanie nie jest potrzebne.',
  },
  opzeggen: {
    title: 'Anuluj subskrypcję',
    meta: 'Anuluj subskrypcję Woonwekker Bellen online, bez okresu wypowiedzenia i bez logowania.',
    paragraphs: [
      'Tutaj anulujesz subskrypcję Bellen. Nie ma okresu wypowiedzenia.',
      'Po rezygnacji nic więcej nie jest pobierane. Zachowujesz dostęp do końca okresu, za który już zapłaciłeś. Jeśli zrezygnujesz w darmowym dniu, nic nie płacisz.',
      'Podaj imię i nazwisko oraz adres e-mail, których użyłeś przy rejestracji, i kliknij „Anuluj subskrypcję”. Logowanie nie jest potrzebne. Od razu zobaczysz potwierdzenie.',
    ],
    withdrawHint: 'Chcesz odstąpić od umowy w ciągu 14 dni od rejestracji i odzyskać pieniądze? Użyj',
  },
  faqNew: {
    what: ['Czym jest Woonwekker?', 'Woonwekker to serwis wyszukiwania i powiadomień. Nie jesteśmy agencją nieruchomości ani pośrednikiem i nie wynajmujemy mieszkań. Oferty pochodzą z publicznych ogłoszeń na innych stronach; kontaktujesz się bezpośrednio z ogłoszeniodawcą.'],
    sources: ['Skąd pochodzą oferty?', 'Z publicznych ogłoszeń na innych stronach: zewnętrzne platformy mieszkaniowe. Przy każdym mieszkaniu widać źródło i datę ostatniego sprawdzenia ogłoszenia.'],
    fresh: ['Czy mieszkania są nadal dostępne?', 'Nie wiemy tego na pewno. Nie pokazujemy ogłoszeń, które w źródle są „w negocjacjach” lub niedostępne, i ukrywamy ogłoszenia, których nie sprawdzaliśmy dłużej niż {days} dni. Zawsze sprawdzaj aktualny status w oryginalnym ogłoszeniu.'],
    contact: ['Jak skontaktować się z ogłoszeniodawcą lub umówić oglądanie?', 'Otwórz mieszkanie i wybierz „Zobacz oryginalne ogłoszenie”. Odpowiadasz bezpośrednio ogłoszeniodawcy, na tamtej stronie. W Woonwekker jest to bezpłatne. Strona źródłowa ma własne warunki. Zewnętrzne platformy mogą wymagać konta lub opłaty, aby odpowiedzieć. Jest to niezależne od Woonwekker.'],
    pay: ['Czy muszę płacić za wyszukiwanie?', 'Nie. Wyszukiwanie, filtrowanie i link do oryginalnego ogłoszenia są bezpłatne. Bellen to opcjonalna subskrypcja dla szybszych powiadomień, dodatkowych filtrów i pierwszeństwa powiadomień: 1 dzień za darmo, potem cena całkowita 18,50 € miesięcznie, z automatycznym odnowieniem do czasu rezygnacji. Dane kontaktowe i linki do ogłoszeń nigdy nie są ukryte za Bellen. Nowe subskrypcje są tymczasowo niedostępne.'],
    alerts: ['Czy dostanę powiadomienia o nowych mieszkaniach?', 'Profile wyszukiwania i powiadomienia e-mail ustawiasz w zakładce Konto. Z Kijken otrzymujesz maksymalnie 3 powiadomienia e-mail tygodniowo; z Bellen natychmiastowe powiadomienia e-mail i pierwszeństwo powiadomień.'],
    photos: ['Dlaczego mieszkanie ma tylko kilka zdjęć?', 'Pokazujemy zdjęcia z oryginalnego ogłoszenia, tak jak udostępnia je strona źródłowa. Więcej zdjęć i danych znajdziesz w oryginalnym ogłoszeniu.'],
    cancel: ['Jak zrezygnować lub odstąpić od umowy?', 'Przez „Anuluj subskrypcję” na dole każdej strony i na koncie, bez okresu wypowiedzenia. Zachowujesz dostęp do końca opłaconego okresu. W ciągu 14 dni od rejestracji możesz odstąpić od umowy przez „Odstąp od umowy”, także bez logowania.'],
  },
  insightA3: {
    title: 'Bezpłatne wyszukiwanie vs Bellen 18,50 €: za co płacisz w Woonwekker',
    intro: 'Wyszukiwanie i kontakt z ogłoszeniodawcą są bezpłatne. Bellen dotyczy wyłącznie szybkości i dodatków.',
    body: '<p>Wiele serwisów z ofertami najmu miesza „zakładanie konta” z „płaceniem”. W Woonwekker to dwie osobne rzeczy, a kontakt z ogłoszeniodawcą nie należy do żadnej z nich: jest zawsze bezpłatny.</p>\n<p><strong>Bezpłatnie (Kijken).</strong> Przeglądasz, filtrujesz i zapisujesz profile wyszukiwania. Przy każdym mieszkaniu widać źródło i datę ostatniego sprawdzenia. Jednym kliknięciem otwierasz oryginalne ogłoszenie na stronie, na której się znajduje, i tam odpowiadasz bezpośrednio ogłoszeniodawcy.</p>\n<p><strong>Bellen: 1 dzień za darmo, potem cena całkowita 18,50 € miesięcznie.</strong> Bellen to opcjonalna subskrypcja dla szybkości i dodatków: natychmiastowe powiadomienia e-mail, dodatkowe filtry i pierwszeństwo powiadomień. Odnawia się co miesiąc, dopóki nie zrezygnujesz. Zrezygnować możesz zawsze online przez <a href="/opzeggen/">Anuluj subskrypcję</a>. Nowe subskrypcje są tymczasowo niedostępne.</p>\n<p><strong>Czym Bellen nie jest.</strong> Woonwekker nie jest agencją nieruchomości ani pośrednikiem i nie wynajmuje mieszkań. Bellen nie jest dostępem do danych kontaktowych ani gwarancją, że dostaniesz mieszkanie. Zasady są w <a href="/voorwaarden/">ogólnych warunkach</a>; ceny i szczegóły w <a href="/prijzen/">cenniku</a>.</p>',
  },
};
