'use strict';
// Portuguese (European).
module.exports = {
  version: 'Versão 1.0, válida a partir de 8 de outubro de 2026. Prevalece o texto neerlandês; as traduções são uma ajuda.',
  voorwaarden: {
    title: 'Condições gerais',
    meta: 'Condições gerais da Woonwekker: serviço de pesquisa e alertas, não é agência imobiliária nem intermediário. Subscrição Bellen, dia grátis, preço, renovação e cancelamento.',
    sections: [
      ['1. Quem somos', 'Vorxeo (Woonwekker), registada na Câmara de Comércio neerlandesa (KvK) com o número 42108778, número de IVA NL005499683B86 («nós»). Woonwekker é uma área de atuação da Vorxeo.'],
      ['2. O que é a Woonwekker', 'A Woonwekker é um serviço de pesquisa e alertas. Não somos uma agência imobiliária nem um intermediário e não arrendamos casas. A oferta vem de anúncios públicos noutros sites; contacta diretamente o anunciante.', 'Não atuamos por conta de senhorios nem de inquilinos, não celebramos contratos de arrendamento e não tratamos pedidos de arrendamento. Em cada casa mostramos a fonte e a data em que verificámos o anúncio pela última vez.'],
      ['3. Sem intermediação, sem garantia', 'Não cobramos comissões de intermediação. Não garantimos que uma casa ainda esteja disponível, que os dados de um anúncio estejam corretos nem que consiga uma casa. Verifique sempre o preço, as condições e a disponibilidade no anúncio original e junto do anunciante.'],
      ['4. Kijken (grátis)', 'Pesquisar, filtrar, favoritos, perfis de pesquisa e a ligação para o anúncio original são grátis, com ou sem conta. Os dados de contacto e as ligações para os anúncios nunca estão atrás de uma subscrição paga.'],
      ['5. Bellen (subscrição paga)', 'Bellen é uma subscrição opcional para rapidez e extras: alertas por e-mail imediatos assim que entra uma casa adequada, filtros adicionais, prioridade nas notificações, o kit de resposta, a lista de documentos e um parceiro de pesquisa. Bellen não dá acesso aos dados de contacto dos anunciantes; esses são grátis para todos.', 'O preço total é de 18,50 € por mês. Na primeira adesão, o primeiro dia é grátis. Depois, a subscrição é renovada automaticamente todos os meses por tempo indeterminado e paga 18,50 € por mês até cancelar.', 'De momento, as novas subscrições estão temporariamente indisponíveis.'],
      ['6. Cancelar', 'Pode cancelar o Bellen online a qualquer momento através de «Cancelar subscrição», no rodapé de cada página ou na sua conta, sem pré-aviso. Depois de cancelar, nada mais é cobrado. Mantém o acesso até ao fim do período que já pagou. Se cancelar durante o dia grátis, não paga nada.'],
      ['7. Direito de livre resolução', 'Tem 14 dias de livre resolução a contar da celebração da subscrição. Nesse prazo pode resolver o contrato sem indicar o motivo através de «Resolver o contrato», também sem iniciar sessão. Se pediu que o Bellen começasse de imediato, ao resolver paga um montante proporcional ao período em que o Bellen já foi prestado. A página Direito de livre resolução contém a informação completa e o formulário de modelo.'],
      ['8. Reembolsos', 'Reembolsamos no prazo de 14 dias, pelo mesmo meio de pagamento que utilizou. Consulte a política de cancelamento e reembolso.'],
      ['9. Anúncios de terceiros', 'Os anúncios, fotografias e textos pertencem aos anunciantes e aos sites onde aparecem. Ligamos para o anúncio original. Responder, visitar e arrendar acontece fora da Woonwekker, segundo as condições desse site e desse anunciante.'],
      ['10. Responsabilidade', 'Não somos responsáveis pelo conteúdo de anúncios de terceiros nem por acordos que faça com um anunciante, salvo em caso de dolo ou negligência grosseira da nossa parte. Os seus direitos legais como consumidor aplicam-se sempre. Nunca transfira dinheiro com base apenas num anúncio.'],
      ['11. Alterações', 'Podemos alterar estas condições. As alterações que afetem uma subscrição em curso são anunciadas com antecedência; pode então cancelar sem custos.'],
      ['12. Lei aplicável', 'Estas condições regem-se pela lei neerlandesa. Como consumidor, mantém a proteção das normas imperativas do país onde reside.'],
    ],
  },
  privacy: {
    title: 'Declaração de privacidade',
    meta: 'Declaração de privacidade da Vorxeo (Woonwekker): que dados o site trata, Google Ads após consentimento, e-mail através da Resend, alojamento e os seus direitos.',
    intro: 'Apenas o que este site faz realmente com dados.',
    sections: [
      ['Responsável', 'A Woonwekker é a responsável pelo tratamento neste site. Número KvK 42108778. Número de IVA NL005499683B86.'],
      'KEEP:1',
      'KEEP:2',
      ['Pagamentos', 'De momento não são processados novos pagamentos; as novas subscrições estão temporariamente indisponíveis. Para uma subscrição Bellen existente, o site define um cookie assinado, ww_bellen, para que o seu acesso neste dispositivo acompanhe o estado da subscrição. Os dados de pagamento de uma subscrição existente são tratados pelo prestador de pagamentos com que pagou. Assim que voltar a estar ativo um prestador de pagamentos, indicá-lo-emos aqui antes de poder pagar.'],
      ['E-mail através da Resend', 'O e-mail de confirmação na adesão e os e-mails sobre a subscrição, o cancelamento ou a resolução são enviados através da Resend, se existir uma chave API no servidor. Sem chave, esse e-mail não é enviado.'],
      ['Cancelar e resolver', 'Se utilizar o formulário «Cancelar subscrição» ou «Resolver o contrato», tratamos o seu nome, o seu e-mail, a data da encomenda se a indicar e a hora de receção. Fazemo-lo para executar o seu pedido e para poder provar que foi recebido a tempo (obrigação legal).'],
      'KEEP:5',
      'KEEP:6',
      ['Alojamento e fotografias', 'O site funciona na Vercel. Ao abrir páginas, a Vercel recebe dados técnicos do pedido, como o endereço IP e o tipo de navegador, necessários para mostrar a página. As fotografias das casas são carregadas diretamente dos servidores de imagens dos sites de origem, que também recebem o seu endereço IP. Quando abre um anúncio original, aplica-se a política de privacidade desse site.'],
      'KEEP:8',
    ],
  },
  terugbetaling: {
    title: 'Política de cancelamento e reembolso',
    meta: 'Cancelamento e reembolso do Woonwekker Bellen: cancele online a qualquer momento, acesso até ao fim do período pago, livre resolução em 14 dias.',
    sections: [
      ['Cancelar', 'Pode cancelar o Bellen online a qualquer momento através de «Cancelar subscrição», sem pré-aviso e sem iniciar sessão. Depois de cancelar, nada mais é cobrado. Mantém o acesso até ao fim do período que já pagou; por esse período não há reembolso parcial, exceto se resolver o contrato dentro do prazo de livre resolução.'],
      ['Dia grátis', 'Se cancelar durante o primeiro dia grátis, não paga nada.'],
      ['Resolver em 14 dias', 'Se resolver o contrato nos 14 dias seguintes à celebração da subscrição, reembolsamos tudo o que pagou. Se pediu que o Bellen começasse de imediato, retemos um montante proporcional ao período em que o Bellen já foi prestado.'],
      ['Como e quando', 'Reembolsamos no prazo de 14 dias após recebermos a sua resolução, pelo mesmo meio de pagamento que utilizou, salvo se aceitar expressamente outra solução. O reembolso não tem custos para si.'],
      ['Cobrança indevida', 'Se for cobrado algo depois de ter cancelado ou resolvido o contrato, reembolsamos o valor na totalidade.'],
    ],
  },
  herroeping: {
    title: 'Direito de livre resolução',
    meta: 'Direito de livre resolução do Woonwekker Bellen: 14 dias, formulário de livre resolução e o botão Resolver o contrato.',
    sections: [
      ['Direito de livre resolução', 'Tem o direito de resolver o contrato do Bellen no prazo de 14 dias sem necessidade de indicar qualquer motivo. O prazo de livre resolução expira 14 dias a contar do dia da celebração do contrato.'],
      ['Como resolver', 'Use o botão «Resolver o contrato» abaixo; não é preciso iniciar sessão. Também pode usar o formulário de modelo ou enviar outra declaração inequívoca, mas não é obrigatório. Para cumprir o prazo, basta enviar a sua declaração antes de terminarem os 14 dias.'],
      ['Efeitos da livre resolução', 'Se resolver o contrato, reembolsamos todos os pagamentos que fez pelo Bellen sem demora injustificada e, em qualquer caso, o mais tardar 14 dias após recebermos a sua resolução. Usamos o mesmo meio de pagamento que utilizou, salvo se aceitar expressamente outra solução; o reembolso não tem custos para si.', 'Se pediu que o Bellen começasse durante o prazo de livre resolução, paga um montante proporcional ao que foi prestado até ao momento em que nos comunica a resolução, em relação ao conjunto do contrato.'],
      ['Confirmação de receção', 'Depois de enviar, vê de imediato uma confirmação com data, hora e referência. Guarde-a. Se o envio de e-mail estiver configurado, enviamos também a confirmação por e-mail.'],
    ],
    modelTitle: 'Modelo de formulário de livre resolução',
    modelNote: '(só deve preencher e devolver o presente formulário se quiser resolver o contrato)',
    modelLines: [
      'Para: Vorxeo (Woonwekker), número KvK 42108778. Pode submetê-lo através do formulário «Resolver o contrato» nesta página.',
      'Pela presente comunico/comunicamos* que resolvo/resolvemos* o meu/nosso* contrato relativo à prestação do seguinte serviço: Woonwekker Bellen',
      'Solicitado em* [data da encomenda]',
      '[Nome do(s) consumidor(es)]',
      '[Endereço do(s) consumidor(es)]',
      '[Assinatura do(s) consumidor(es)] (só no caso de o presente formulário ser notificado em papel)',
      '[Data (DD-MM-AAAA)]',
    ],
    modelFoot: '* Riscar o que não interessa.',
    formTitle: 'Resolver o contrato',
    formIntro: 'Indique o nome e o e-mail com que se registou. Não é preciso iniciar sessão.',
  },
  opzeggen: {
    title: 'Cancelar subscrição',
    meta: 'Cancele online a sua subscrição Woonwekker Bellen, sem pré-aviso e sem iniciar sessão.',
    paragraphs: [
      'Aqui cancela a sua subscrição Bellen. Não há pré-aviso.',
      'Depois de cancelar, nada mais é cobrado. Mantém o acesso até ao fim do período que já pagou. Se cancelar durante o dia grátis, não paga nada.',
      'Indique o nome e o e-mail com que se registou e clique em «Cancelar subscrição». Não é preciso iniciar sessão. Vê uma confirmação de imediato.',
    ],
    withdrawHint: 'Quer resolver o contrato nos 14 dias seguintes à adesão e receber o seu dinheiro de volta? Use',
  },
  faqNew: {
    what: ['O que é a Woonwekker?', 'A Woonwekker é um serviço de pesquisa e alertas. Não somos uma agência imobiliária nem um intermediário e não arrendamos casas. A oferta vem de anúncios públicos noutros sites; contacta diretamente o anunciante.'],
    sources: ['De onde vem a oferta?', 'De anúncios públicos noutros sites: plataformas imobiliárias externas. Cada casa mostra a fonte e a data em que verificámos o anúncio pela última vez.'],
    fresh: ['As casas ainda estão disponíveis?', 'Não temos a certeza. Não mostramos anúncios que na fonte estão «em negociação» ou indisponíveis, e ocultamos anúncios que não verificamos há mais de {days} dias. Verifique sempre o estado atual no anúncio original.'],
    contact: ['Como contacto o anunciante ou marco uma visita?', 'Abra uma casa e escolha «Ver o anúncio original». Responde diretamente ao anunciante, nesse site. Na Woonwekker é grátis. O site de origem tem as suas próprias condições. As plataformas externas podem exigir uma conta ou pagamento para responder. Isso é independente da Woonwekker.'],
    pay: ['Tenho de pagar para pesquisar?', 'Não. Pesquisar, filtrar e a ligação para o anúncio original são grátis. Bellen é uma subscrição opcional para alertas mais rápidos, filtros adicionais e prioridade nas notificações: 1 dia grátis, depois preço total de 18,50 € por mês, com renovação automática até cancelar. Os dados de contacto e as ligações para os anúncios nunca estão atrás do Bellen. As novas subscrições estão temporariamente indisponíveis.'],
    alerts: ['Recebo avisos de casas novas?', 'Configura perfis de pesquisa e avisos por e-mail em Conta. Com Kijken recebe no máximo 3 alertas por e-mail por semana; com Bellen, alertas por e-mail imediatos e prioridade nas notificações.'],
    photos: ['Porque é que uma casa tem só algumas fotografias?', 'Mostramos as fotografias do anúncio original, tal como o site de origem as disponibiliza. Mais fotografias e dados encontram-se no anúncio original.'],
    cancel: ['Como cancelo ou resolvo o contrato?', 'Através de «Cancelar subscrição», no rodapé de cada página e na sua conta, sem pré-aviso. Mantém o acesso até ao fim do período pago. Nos 14 dias seguintes à adesão pode resolver o contrato através de «Resolver o contrato», também sem iniciar sessão.'],
  },
  insightA3: {
    title: 'Pesquisa grátis vs Bellen 18,50 €: o que paga na Woonwekker',
    intro: 'Pesquisar e contactar o anunciante é grátis. O Bellen é apenas rapidez e extras.',
    body: '<p>Muitos sites de arrendamento misturam «criar uma conta» com «pagar». Na Woonwekker são coisas separadas, e contactar um anunciante não pertence a nenhuma delas: é sempre grátis.</p>\n<p><strong>Grátis (Kijken).</strong> Navega, filtra e guarda perfis de pesquisa. Cada casa mostra a fonte e a data da última verificação. Com um clique abre o anúncio original no site onde aparece, e aí responde diretamente ao anunciante.</p>\n<p><strong>Bellen: 1 dia grátis, depois preço total de 18,50 € por mês.</strong> O Bellen é uma subscrição opcional para rapidez e extras: alertas por e-mail imediatos, filtros adicionais e prioridade nas notificações. É renovado todos os meses até cancelar. Pode cancelar sempre online através de <a href="/opzeggen/">Cancelar subscrição</a>. As novas subscrições estão temporariamente indisponíveis.</p>\n<p><strong>O que o Bellen não é.</strong> A Woonwekker não é uma agência imobiliária nem um intermediário e não arrenda casas. O Bellen não dá acesso a dados de contacto nem garante que consiga uma casa. As regras estão nas <a href="/voorwaarden/">condições gerais</a>; preços e detalhes em <a href="/prijzen/">preços</a>.</p>',
  },
};
