'use strict';
module.exports = {
  version: 'Versiunea 1.0, valabilă de la 8 octombrie 2026. Textul în neerlandeză prevalează; traducerile sunt un ajutor.',
  voorwaarden: {
    title: 'Condiții generale',
    meta: 'Condițiile generale Woonwekker: serviciu de căutare și alerte, nu agenție imobiliară sau intermediar. Abonamentul Bellen, ziua gratuită, preț, reînnoire și anulare.',
    sections: [
      ['1. Cine suntem', 'Vorxeo (Woonwekker), înregistrată la Camera de Comerț din Țările de Jos (KvK) sub numărul 42108778, cod TVA NL005499683B86 („noi”). Woonwekker este o divizie a Vorxeo. Vorxeo: Keizersgracht 520H, 1017 EK Amsterdam, Nederland. +31 85 212 77 69. support@vorxeo.com.'],
      ['2. Ce este Woonwekker', 'Woonwekker este un serviciu de căutare și alerte. Nu suntem agenție imobiliară sau intermediar și nu închiriem locuințe. Ofertele provin din anunțuri publice de pe alte site-uri; contactezi direct ofertantul.', 'Nu acționăm în numele proprietarilor sau al chiriașilor, nu încheiem contracte de închiriere și nu procesăm cereri de închiriere. La fiecare locuință afișăm sursa și data la care am verificat ultima dată anunțul.'],
      ['3. Fără intermediere, fără garanție', 'Nu percepem comision de intermediere. Nu garantăm că o locuință este încă disponibilă, că datele dintr-un anunț sunt corecte sau că vei obține o locuință. Verifică întotdeauna prețul, condițiile și disponibilitatea în anunțul original și la ofertant.'],
      ['4. Kijken (gratuit)', 'Căutarea, filtrarea, favoritele, profilurile de căutare și linkul către anunțul original sunt gratuite, cu sau fără cont. Datele de contact și linkurile către anunțuri nu sunt niciodată în spatele unui abonament plătit.'],
      ['5. Bellen (abonament plătit)', 'Bellen este un abonament opțional pentru viteză și extra: alerte imediate pe e-mail de îndată ce apare o locuință potrivită, filtre suplimentare, prioritate la notificări, kitul de răspuns, lista de documente și un partener de căutare. Bellen nu oferă acces la datele de contact ale ofertanților; acestea sunt gratuite pentru toată lumea.', 'Prețul total este de 18,50 € pe lună. La prima înscriere, prima zi este gratuită. După aceea, abonamentul se reînnoiește automat în fiecare lună pe durată nedeterminată și plătești 18,50 € pe lună până când îl anulezi.', 'În acest moment, abonamentele noi sunt temporar indisponibile.'],
      ['6. Anulare', 'Poți anula Bellen online oricând prin „Anulează abonamentul”, în subsolul fiecărei pagini sau în contul tău, fără perioadă de preaviz. După anulare nu se mai încasează nimic. Păstrezi accesul până la sfârșitul perioadei pe care ai plătit-o deja. Dacă anulezi în ziua gratuită, nu plătești nimic.'],
      ['7. Dreptul de retragere', 'Ai 14 zile de retragere de la încheierea abonamentului. În această perioadă te poți retrage din contract fără a indica motivul prin „Retragere din contract”, inclusiv fără autentificare. Dacă ai cerut ca Bellen să înceapă imediat, la retragere plătești o sumă proporțională cu perioada în care Bellen a fost deja furnizat. Pagina Dreptul de retragere conține informațiile complete și formularul tip.'],
      ['8. Rambursări', 'Efectuăm rambursările în 14 zile, prin aceeași metodă de plată pe care ai folosit-o. Vezi politica de anulare și rambursare.'],
      ['9. Anunțurile altora', 'Anunțurile, fotografiile și textele aparțin ofertanților și site-urilor pe care apar. Trimitem către anunțul original. Răspunsul, vizionarea și închirierea au loc în afara Woonwekker, în condițiile acelui site și ale acelui ofertant.'],
      ['10. Răspundere', 'Nu răspundem pentru conținutul anunțurilor altora sau pentru înțelegerile pe care le faci cu un ofertant, cu excepția intenției sau a imprudenței grave din partea noastră. Drepturile tale legale de consumator se aplică întotdeauna. Nu transfera niciodată bani doar pe baza unui anunț.'],
      ['11. Modificări', 'Putem modifica aceste condiții. Modificările care afectează un abonament în curs le anunțăm în prealabil; atunci poți anula fără costuri.'],
      ['12. Legea aplicabilă', 'Aceste condiții sunt guvernate de legea neerlandeză. Ca și consumator, păstrezi protecția normelor imperative din țara în care locuiești.'],
    ],
  },
  privacy: {
    title: 'Declarație de confidențialitate',
    meta: 'Declarația de confidențialitate Vorxeo (Woonwekker): ce date prelucrează site-ul, Google Ads după consimțământ, e-mail prin Resend, găzduire și drepturile tale.',
    intro: 'Doar ce face efectiv acest site cu datele.',
    sections: [
      ['Operator', 'Woonwekker este operatorul prelucrărilor de pe acest site. Număr KvK 42108778. Cod TVA NL005499683B86. Vorxeo: Keizersgracht 520H, 1017 EK Amsterdam, Nederland. +31 85 212 77 69. support@vorxeo.com.'],
      'KEEP:1',
      'KEEP:2',
      ['Plăți', 'În acest moment nu se procesează plăți noi; abonamentele noi sunt temporar indisponibile. Pentru un abonament Bellen existent, site-ul setează un cookie semnat, ww_bellen, astfel încât accesul tău pe acest dispozitiv să urmeze starea abonamentului. Datele de plată ale unui abonament existent sunt prelucrate de furnizorul de plăți prin care ai plătit. De îndată ce un furnizor de plăți va fi din nou activ, îl vom menționa aici înainte să poți plăti.'],
      ['E-mail prin Resend', 'E-mailul de confirmare la înscriere și e-mailurile despre abonament, anulare sau retragere sunt trimise prin Resend, dacă pe server există o cheie API. Fără cheie, acel e-mail nu este trimis.'],
      ['Anulare și retragere', 'Dacă folosești formularul „Anulează abonamentul” sau „Retragere din contract”, prelucrăm numele tău, adresa de e-mail, data comenzii dacă o completezi și momentul primirii. Facem acest lucru pentru a da curs cererii și pentru a putea dovedi că a fost primită la timp (obligație legală).'],
      'KEEP:5',
      'KEEP:6',
      ['Găzduire și fotografii', 'Site-ul rulează pe Vercel. Când deschizi pagini, Vercel primește date tehnice ale cererii, cum ar fi adresa IP și tipul de browser, necesare pentru afișarea paginii. Fotografiile locuințelor se încarcă direct de pe serverele de imagini ale site-urilor sursă, care primesc și ele adresa ta IP. Când deschizi un anunț original, se aplică politica de confidențialitate a acelui site.'],
      'KEEP:8',
    ],
  },
  terugbetaling: {
    title: 'Politica de anulare și rambursare',
    meta: 'Anulare și rambursare pentru Woonwekker Bellen: anulare online oricând, acces până la sfârșitul perioadei plătite, retragere în 14 zile.',
    sections: [
      ['Anulare', 'Poți anula Bellen online oricând prin „Anulează abonamentul”, fără perioadă de preaviz și fără autentificare. După anulare nu se mai încasează nimic. Păstrezi accesul până la sfârșitul perioadei pe care ai plătit-o deja; pentru acea perioadă nu există rambursare parțială, cu excepția retragerii în termenul de retragere.'],
      ['Ziua gratuită', 'Dacă anulezi în prima zi, cea gratuită, nu plătești nimic.'],
      ['Retragere în 14 zile', 'Dacă te retragi în 14 zile de la încheierea abonamentului, îți rambursăm tot ce ai plătit. Dacă ai cerut ca Bellen să înceapă imediat, reținem o sumă proporțională cu perioada în care Bellen a fost deja furnizat.'],
      ['Cum și când', 'Rambursăm în 14 zile de la primirea retragerii tale, prin aceeași metodă de plată pe care ai folosit-o, cu excepția cazului în care accepți în mod expres altceva. Rambursarea nu te costă nimic.'],
      ['Încasare nedatorată', 'Dacă după anulare sau retragere se încasează totuși ceva, îți rambursăm integral suma.'],
    ],
  },
  herroeping: {
    title: 'Dreptul de retragere',
    meta: 'Dreptul de retragere pentru Woonwekker Bellen: 14 zile, formularul tip de retragere și butonul Retragere din contract.',
    sections: [
      ['Dreptul de retragere', 'Ai dreptul de a te retrage din contractul Bellen în termen de 14 zile, fără a preciza motivele. Perioada de retragere expiră după 14 zile de la data încheierii contractului.'],
      ['Cum te retragi', 'Folosește butonul „Retragere din contract” de mai jos; nu este nevoie de autentificare. Poți folosi și formularul tip sau trimite o altă declarație neechivocă, dar nu este obligatoriu. Pentru a respecta termenul este suficient să trimiți declarația înainte de expirarea celor 14 zile.'],
      ['Efectele retragerii', 'Dacă te retragi, îți vom rambursa toate plățile făcute pentru Bellen fără întârzieri nejustificate și, în orice caz, în cel mult 14 zile de la primirea retragerii. Folosim aceeași metodă de plată pe care ai folosit-o, cu excepția cazului în care accepți în mod expres altceva; rambursarea nu te costă nimic.', 'Dacă ai solicitat ca Bellen să înceapă în perioada de retragere, plătești o sumă proporțională cu ce a fost furnizat până în momentul în care ne informezi că te retragi, raportat la executarea integrală a contractului.'],
      ['Confirmare de primire', 'După trimitere vezi imediat o confirmare cu data, ora și o referință. Păstreaz-o. Dacă trimiterea de e-mailuri este configurată, îți trimitem confirmarea și pe e-mail.'],
    ],
    modelTitle: 'Model de formular de retragere',
    modelNote: '(completați și returnați acest formular doar dacă doriți să vă retrageți din contract)',
    modelLines: [
      'Către: Vorxeo (Woonwekker), număr KvK 42108778. Îl puteți transmite prin formularul „Retragere din contract” de pe această pagină. Vorxeo: Keizersgracht 520H, 1017 EK Amsterdam, Nederland. +31 85 212 77 69. support@vorxeo.com.',
      'Vă informez/informăm* prin prezenta cu privire la retragerea mea/noastră* din contractul referitor la prestarea următorului serviciu: Woonwekker Bellen',
      'Comandat la data* [data comenzii]',
      '[Numele consumatorului (consumatorilor)]',
      '[Adresa consumatorului (consumatorilor)]',
      '[Semnătura consumatorului (consumatorilor)] (doar în cazul în care acest formular este notificat pe hârtie)',
      '[Data (ZZ-LL-AAAA)]',
    ],
    modelFoot: '* Se elimină mențiunea inutilă.',
    formTitle: 'Retragere din contract',
    formIntro: 'Completează numele și adresa de e-mail cu care te-ai înscris. Nu este nevoie de autentificare.',
  },
  opzeggen: {
    title: 'Anulează abonamentul',
    meta: 'Anulează online abonamentul Woonwekker Bellen, fără perioadă de preaviz și fără autentificare.',
    paragraphs: [
      'Aici îți anulezi abonamentul Bellen. Nu există perioadă de preaviz.',
      'După anulare nu se mai încasează nimic. Păstrezi accesul până la sfârșitul perioadei pe care ai plătit-o deja. Dacă anulezi în ziua gratuită, nu plătești nimic.',
      'Completează numele și adresa de e-mail cu care te-ai înscris și apasă „Anulează abonamentul”. Nu este nevoie de autentificare. Vezi imediat o confirmare.',
    ],
    withdrawHint: 'Vrei să te retragi din contract în 14 zile de la înscriere și să îți primești banii înapoi? Folosește',
  },
  faqNew: {
    what: ['Ce este Woonwekker?', 'Woonwekker este un serviciu de căutare și alerte. Nu suntem agenție imobiliară sau intermediar și nu închiriem locuințe. Ofertele provin din anunțuri publice de pe alte site-uri; contactezi direct ofertantul.'],
    sources: ['De unde provin ofertele?', 'Din anunțuri publice de pe alte site-uri: platforme imobiliare externe. Fiecare locuință afișează sursa și data la care am verificat ultima dată anunțul.'],
    fresh: ['Mai sunt disponibile locuințele?', 'Nu știm sigur. Nu afișăm anunțurile care la sursă sunt „în negociere” sau indisponibile și ascundem anunțurile pe care nu le-am verificat de mai mult de {days} zile. Verifică întotdeauna starea actuală în anunțul original.'],
    contact: ['Cum contactez ofertantul sau programez o vizionare?', 'Deschide o locuință și alege „Vezi anunțul original”. Răspunzi direct ofertantului, pe acel site. Pe Woonwekker este gratuit. Site-ul sursă are propriile condiții. Platformele externe pot solicita un cont sau o plată pentru a răspunde. Acest lucru este separat de Woonwekker.'],
    pay: ['Trebuie să plătesc ca să caut?', 'Nu. Căutarea, filtrarea și linkul către anunțul original sunt gratuite. Bellen este un abonament opțional pentru alerte mai rapide, filtre suplimentare și prioritate la notificări: 1 zi gratuită, apoi preț total 18,50 € pe lună, cu reînnoire automată până la anulare. Datele de contact și linkurile către anunțuri nu sunt niciodată în spatele Bellen. Abonamentele noi sunt temporar indisponibile.'],
    alerts: ['Primesc notificări despre locuințe noi?', 'Setezi profiluri de căutare și notificări pe e-mail în Cont. Cu Kijken primești cel mult 3 alerte pe e-mail pe săptămână; cu Bellen, alerte imediate pe e-mail și prioritate la notificări.'],
    photos: ['De ce o locuință are doar câteva fotografii?', 'Afișăm fotografiile din anunțul original, așa cum le oferă site-ul sursă. Mai multe fotografii și date găsești în anunțul original.'],
    cancel: ['Cum anulez sau mă retrag din contract?', 'Prin „Anulează abonamentul”, în subsolul fiecărei pagini și în cont, fără perioadă de preaviz. Păstrezi accesul până la sfârșitul perioadei plătite. În 14 zile de la înscriere te poți retrage din contract prin „Retragere din contract”, inclusiv fără autentificare.'],
  },
  insightA3: {
    title: 'Căutare gratuită vs Bellen 18,50 €: pentru ce plătești pe Woonwekker',
    intro: 'Căutarea și contactul cu ofertantul sunt gratuite. Bellen înseamnă doar viteză și extra.',
    body: '<p>Multe site-uri de închirieri amestecă „crearea unui cont” cu „plata”. Pe Woonwekker acestea sunt separate, iar contactul cu un ofertant nu ține de niciuna: este întotdeauna gratuit.</p>\n<p><strong>Gratuit (Kijken).</strong> Răsfoiești, filtrezi și salvezi profiluri de căutare. Fiecare locuință afișează sursa și data ultimei verificări. Cu un clic deschizi anunțul original pe site-ul unde apare și acolo răspunzi direct ofertantului.</p>\n<p><strong>Bellen: 1 zi gratuită, apoi preț total 18,50 € pe lună.</strong> Bellen este un abonament opțional pentru viteză și extra: alerte imediate pe e-mail, filtre suplimentare și prioritate la notificări. Se reînnoiește lunar până îl anulezi. Poți anula oricând online prin <a href="/opzeggen/">Anulează abonamentul</a>. Abonamentele noi sunt temporar indisponibile.</p>\n<p><strong>Ce nu este Bellen.</strong> Woonwekker nu este agenție imobiliară sau intermediar și nu închiriază locuințe. Bellen nu înseamnă acces la date de contact și nici garanția că vei obține o locuință. Regulile sunt în <a href="/voorwaarden/">condițiile generale</a>; prețuri și detalii la <a href="/prijzen/">prețuri</a>.</p>',
  },
};
